#!/usr/bin/env python3
"""
Display Configuration Code Generator
Dinamik display implementasyonlarını configuration dosyasından otomatik kod üretir
"""

import json
import os
import sys
from pathlib import Path
from datetime import datetime


class DisplayCodeGenerator:
    def __init__(self, config_file_path):
        self.config_file = config_file_path
        self.config = None
        self.project_root = None
        self.load_configuration()
    
    def load_configuration(self):
        """JSON konfigürasyon dosyasını yükle"""
        try:
            with open(self.config_file, 'r') as f:
                self.config = json.load(f)
            # Proje root'u belirle
            self.project_root = Path(self.config_file).parent
            print(f"✓ Konfigürasyon yüklendi: {self.config_file}")
        except FileNotFoundError:
            print(f"✗ Konfigürasyon dosyası bulunamadı: {self.config_file}")
            sys.exit(1)
        except json.JSONDecodeError as e:
            print(f"✗ JSON parse hatası: {e}")
            sys.exit(1)
    
    def generate_autogen_c_file(self):
        """AppDisplayManager_Autogen.c dosyasını oluştur"""
        disp_config = self.config['displayConfig']
        customer_path = disp_config.get('customerPath', '')
        custom_file_name = disp_config.get('customFileName', '')
        display_type = disp_config.get('type', 'unknown')
        
        # Include path'ini oluştur
        include_path = os.path.join(customer_path, custom_file_name)
        include_path = include_path.replace('\\', '/')
        
        content = f"""/******************************************************************************
* #Author       : Zafer Satilmis
* #Revision     : Auto-generated
* #Date         : {datetime.now().strftime('%d %b %Y - %H:%M:%S')}
* #File Name    : AppDisplayManager_Autogen.c
*******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* This file is automatically generated from display_config.json
* Display Type: {display_type}
*******************************************************************************/
#define SHOW_PAGE_DBG_MSG  (ENABLE)

/********************************* INCLUDES ***********************************/
#include "{include_path}"

/****************************** MACRO DEFINITIONS *****************************/


/******************************* TYPE DEFINITIONS *****************************/

/********************************** VARIABLES *********************************/

/***************************** STATIC FUNCTIONS  ******************************/

/***************************** PUBLIC FUNCTIONS  ******************************/

/******************************** End Of File *********************************/
"""
        return content
    
    def resolve_custom_file_path(self):
        """Müşteri dosyasının tam path'ini resolve et"""
        disp_config = self.config['displayConfig']
        customer_path = disp_config.get('customerPath', '')
        custom_file_name = disp_config.get('customFileName', '')
        
        # Relative path ise project root'dan resolve yap
        if not Path(customer_path).is_absolute():
            full_path = self.project_root.parent.parent.parent.parent / customer_path / (custom_file_name)
        else:
            full_path = Path(customer_path) / (custom_file_name)
        
        if full_path.exists():
            print(f"✓ Müşteri Display dosyası bulundu: {full_path}")
            return str(full_path)
        else:
            print(f"⚠ Uyarı: Müşteri Display dosyası bulunamadı: {full_path}")
            return None
    
    def validate_config(self):
        """Konfigürasyonu doğrula"""
        try:
            disp_config = self.config['displayConfig']
            required_fields = ['devName', 'type', 'customerPath', 'customFileName', 'autoGenFileName']
            
            for field in required_fields:
                if field not in disp_config:
                    print(f"✗ Eksik alan: {field}")
                    return False
            
            # Müşteri dosyasının var olup olmadığını kontrol et
            custom_file = self.resolve_custom_file_path()
            if not custom_file:
                print("⚠ Uyarı: Müşteri Display dosyası bulunamadı")
            
            print("✓ Konfigürasyon doğrulama başarılı")
            return True
        except Exception as e:
            print(f"✗ Doğrulama hatası: {e}")
            return False
    
    def generate_auto_file(self):
        """AppDisplayManager_Autogen.c dosyasını oluştur"""
        disp_config = self.config['displayConfig']
        auto_gen_filename = disp_config.get('autoGenFileName', 'AppDisplayManager_Autogen.c')
        output_path = self.project_root / auto_gen_filename
        
        content = self.generate_autogen_c_file()
        
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✓ Otomatik dosya oluşturuldu: {output_path}")
            return output_path
        except Exception as e:
            print(f"✗ Dosya yazma hatası: {e}")
            sys.exit(1)
    
    def generate(self):
        """Tüm kod üretim adımlarını çalıştır"""
        print("\n" + "="*60)
        print("Display Code Generator")
        print("="*60 + "\n")
        
        if not self.validate_config():
            sys.exit(1)
        
        self.generate_auto_file()
        print("\n" + "="*60)
        print("✓ Kod üretimi tamamlandı!")
        print("="*60 + "\n")


def main():
    if len(sys.argv) < 2:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        config_file = os.path.join(script_dir, 'display_config.json')
    else:
        config_file = sys.argv[1]
    
    generator = DisplayCodeGenerator(config_file)
    generator.generate()


if __name__ == '__main__':
    main()
