/******************************************************************************
* Auto-generated fs_port_config.h
* customer     : ZD_2622
* version      : 1.1
* releaseDate  : 2026-03-20
* generated by : generate_fs_port_config.py
* generated on : 2026-03-22 13:03:25
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: ZD_2622
* Generated from customer time_config.json. Only used units are included.
******************************************************************************/

#ifndef __FS_PORT_CONFIG_H__
#define __FS_PORT_CONFIG_H__

#include "error.h"

/* Error codes used by fs_port but not in CycloneTCP error.h */
#ifndef ERROR_NOT_READY
   #define ERROR_NOT_READY  9999
#endif
#ifndef ERROR_ALREADY_EXISTS
   #define ERROR_ALREADY_EXISTS  9998
#endif

#define USE_FATFS 1

/****************************** HW DRIVER INCLUDE *******************************/
#define FATFS_CHIP_NAME "W25Q128JV"

#include "Ext_spi_flash_W25Qxx_driver.h"

/****************************** MACRO DEFINITIONS *******************************/
#define FATFS_CAPACITY_BYTES     (16777216)

#define FATFS_GEOMETRY_PAGE_SIZE (256)
#define FATFS_GEOMETRY_SECTOR_SIZE (4096)
#define FATFS_GEOMETRY_BLOCK_SIZE (65536)
#define FATFS_GEOMETRY_BASE_ADDR (0x080A0000)

#define FATFS_TIMING_PAGE_PROGRAM_TIME_MS (3)
#define FATFS_TIMING_SECTOR_ERASE_TIME_MS (50)
#define FATFS_TIMING_BLOCK_ERASE_TIME_MS (150)

#define STORAGE_DRV_FUNC_READ    extFlashW25QxxRead
#define STORAGE_DRV_FUNC_PROG    extFlashW25QxxProg
#define STORAGE_DRV_FUNC_ERASE   extFlashW25QxxErase
#define STORAGE_DRV_FUNC_SYNC    extFlashW25QxxSync

/****************************** INCLUDE FS *******************************/
//FatFs port?
#if defined(USE_FATFS)
   #include "fs_port_fatfs.h"
//littleFS port?
#elif defined(USE_LITTLEFS)
   #include "fs_port_littlefs.h"
//FlashFS port?
#elif defined(USE_FLASHFS)
   #include "fs_port_flashFS.h"
//FlashLink port?
#elif defined(USE_FLASHLINK)
   #include "fs_port_flashLink.h"
//PC Simulator / Windows / POSIX (JSON: pc_simulator veya _WIN32/__linux__)
#elif defined(USE_PC_SIMULATOR)
   #include "fs_port_posix.h"
//Custom port?
#elif defined(USE_CUSTOM_FS)
   #include "fs_port_custom.h"
//FS not found in fsLib (activeFsName not in fsLib)
#elif defined(USE_NOT_FOUND_FS)
   #error "USE_NOT_FOUND_FS fs is not found"
//FS not used (useStore=false)
#elif defined(USE_NOT_USED_FS)
   #error "USE_NOT_USED_FS fs is not used"
#endif

#endif /* __FS_PORT_CONFIG_H__ */
