/******************************************************************************
* designed by  : Zafer Satilmis
* hype-man     : Pentagram/Mezarkabul - Secret Missile
* customer     : LinuxGcc
* version      : 1.1
* releaseDate  : 2026-04-06
* generated by : generate_protocol_config.py
* generated on : 2026-04-06 19:32:10
*******************************************************************************/

/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: LinuxGcc
* Generated from customer protocol_config.json. Only used units are included.
******************************************************************************/
/****************************** IFNDEF & DEFINE ******************************/
#ifndef __CUS_PROTOCOL_CONFIG_H__
#define __CUS_PROTOCOL_CONFIG_H__
/********************************* INCLUDES **********************************/
#include "Project_Conf.h"
/***************************** MACRO DEFINITIONS *****************************/

#define ACTIVE_PROTOCOL_NUMBER (1)

/****** PROTOCOL - ORION_TLV *****************************/
#include "Application/AppZMeterGw/Services/Protocol/inc/AppProtocolOrionTlv.h"
#define APP_ORION_TLV_PROTOCOL_INIT_FUNC(serialNumber)   appProtocolOrionTlvInit(serialNumber)
#define APP_ORION_TLV_PROTOCOL_START_FUNC()              appProtocolOrionTlvStart()
#define APP_ORION_TLV_PROTOCOL_STOP_FUNC()               appProtocolOrionTlvStop()
#define APP_ORION_TLV_PROTOCOL_PUT_INCOMING_FUNC(channel, data, dataLength) appProtocolOrionTlvPutIncomingMessage(channel, data, dataLength)

#define ORION_TLV_DEFAULT_SERVER_IP       "127.0.0.1"
#define ORION_TLV_DEFAULT_PUSH_PORT       (1883)
#define ORION_TLV_DEFAULT_DEVICE_IP       "127.0.0.1"
#define ORION_TLV_DEFAULT_PULL_PORT       (2622)

/******* PROTOCOL - INIT *****************************/
#define INIT_PROTOCOLS(setErrorFlag)   \
                                    do{ \
                                        setErrorFlag = 0;\
                                        if(!setErrorFlag) {setErrorFlag |= APP_ORION_TLV_PROTOCOL_INIT_FUNC(setErrorFlag); zosDelay(1000); } \
                                        if(!setErrorFlag) {setErrorFlag |= APP_ORION_TLV_PROTOCOL_START_FUNC(); zosDelay(1000); } \
                                    } while(0)


/********************************* SENSOR DEFINITIONS *************************/
#define ACTIVE_SENDOR_NUMBER (1)

#include "Application/AppZMeterGw/Services/Protocol/Test_Server/MeterTcpComm.h"
#define SENSOR_ELECTRICITYMETER_INITIALIZE_FUNC(setErrorFlag)   \
                                    do{ \
                                        /* Sensor initialization code here */ \
                                        MeterCommInterface_t meterComm = { \
                                            .meterCommInit        = meterTcpCommInit, \
                                            .meterCommSend        = meterTcpCommSend, \
                                            .meterCommReceive     = meterTcpCommReceive, \
                                            .meterCommSetBaudrate = meterTcpCommSetBaudrate, \
                                        }; \
                                        setErrorFlag |= appMeterOperationsStart(&meterComm); \

                                    } while(0)

#define INIT_SENSORS(setErrorFlag)   \
                                    do{ \
                                        setErrorFlag = 0;\
                                        if(!setErrorFlag) SENSOR_ELECTRICITYMETER_INITIALIZE_FUNC(setErrorFlag); \
                                    } while(0)


/******************************* TYPE DEFINITIONS *****************************/

/************************* GLOBAL VARIBALE REFERENCES *************************/

/************************* GLOBAL FUNCTION DEFINITIONS ************************/

#endif /* __CUS_PROTOCOL_CONFIG_H__ */

/********************************* End Of File ********************************/
