/******************************************************************************
* designed by   : Zafer Satilmis
* hype-man      : Judas Priest - Night Crawler
* customer      : ZD_0101
* generated by  : generate_logger_service.py
* generated on  : 2026-03-25 16:33:36
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: ZD_0101
* Generated from customer logger_config.json via generate_logger_service.py.
******************************************************************************/
#ifndef __LOGGER_SERVICE_CONFIG_H__
#define __LOGGER_SERVICE_CONFIG_H__

#include "ZD_0101/Logger/Cus_LoggerService_Conf.h"

RETURN_STATUS appLogStartLoggers(void);

#endif /* __LOGGER_SERVICE_CONFIG_H__ */

/********************************* End Of File ********************************/
