/******************************************************************************
* designed by   : Zafer Satilmis
* hype-man      : Judas Priest - Night Crawler
* customer      : LinuxGcc
* generated by  : generate_fs_port_config.py
* generated on  : 2026-04-20 08:11:29
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: LinuxGcc
* Generated from customer fs_config.json.
******************************************************************************/
#ifndef __FS_PORT_CONFIG_H__
#define __FS_PORT_CONFIG_H__

#include "LinuxGcc/Fs/Cus_Fs_Port_Config.h"

#endif /* __FS_PORT_CONFIG_H__ */
