/******************************************************************************
* designed by   : Zafer Satilmis
* hype-man      : Judas Priest - Night Crawler
* customer      : ZD_0101
* generated by  : generate_fs_port_config.py
* generated on  : 2026-03-22 18:34:54
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: ZD_0101
* Generated from customer fs_config.json.
******************************************************************************/
#ifndef __FS_PORT_CONFIG_H__
#define __FS_PORT_CONFIG_H__

#include "ZD_0101/Fs/cus_fs_port_config.h"

#endif /* __FS_PORT_CONFIG_H__ */
