#!/usr/bin/env python3
"""
Generate fs_port_config.h from customer's fs_config.json.

Usage:
  python generate_fs_port_config.py --customer ZD_0101
  python generate_fs_port_config.py -h
"""

import argparse
import json
import os
import sys
from datetime import datetime

# Map fs name (from activeFsName) -> USE_ macro
FS_NAME_TO_MACRO = {
    "fatfs":       "USE_FATFS",
    "littlefs":    "USE_LITTLEFS",
    "flashfs":     "USE_FLASHFS",
    "flashlink":   "USE_FLASHLINK",
    "pc_simulator": "USE_PC_SIMULATOR",
    "custom":      "USE_CUSTOM_FS",
}


def parse_size_to_bytes(size_val) -> int:
    """Parse int or string like '128K', '1M' into bytes."""
    if isinstance(size_val, int):
        return size_val
    s = str(size_val).strip().upper()
    if s.isdigit():
        return int(s)
    if s.endswith("K"):
        return int(float(s[:-1]) * 1024)
    if s.endswith("M"):
        return int(float(s[:-1]) * 1024 * 1024)
    raise ValueError(f"Unsupported size format: {size_val}")


def generate_header(cfg: dict, customer: str, script_name: str) -> str:
    """Generate fs_port_config.h content."""
    version = cfg.get("version", "0.0")
    release_date = cfg.get("releaseDate", "")
    store = cfg.get("store", {})
    use_store = store.get("useStore", False)
    active_fs_name = store.get("activeFsName", "").strip().lower()
    print(f"\033[92mSELECTED FS NAME: {active_fs_name}\033[0m")
    fs_lib = store.get("fsLib", {})
    fs_config = fs_lib.get(active_fs_name) if active_fs_name else None

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []
    lines.append("/******************************************************************************")
    lines.append("* Auto-generated fs_port_config.h")
    lines.append(f"* customer     : {customer}")
    lines.append(f"* version      : {version}")
    lines.append(f"* releaseDate  : {release_date}")
    lines.append(f"* generated by : {script_name}")
    lines.append(f"* generated on : {now_str}")
    lines.append("******************************************************************************/")
    lines.append("")
    lines.append("#ifndef __FS_PORT_CONFIG_H__")
    lines.append("#define __FS_PORT_CONFIG_H__")
    lines.append("")
    lines.append("#include \"error.h\"")
    lines.append("")
    lines.append("/* Error codes used by fs_port but not in CycloneTCP error.h */")
    lines.append("#ifndef ERROR_NOT_READY")
    lines.append("   #define ERROR_NOT_READY  9999")
    lines.append("#endif")
    lines.append("#ifndef ERROR_ALREADY_EXISTS")
    lines.append("   #define ERROR_ALREADY_EXISTS  9998")
    lines.append("#endif")
    lines.append("")

    if not use_store:
        lines.append("#define USE_NOT_USED_FS 1")
        print(f"\033[91mFS NOT USED\033[0m")
    elif fs_config is None:        
        lines.append("#define USE_NOT_FOUND_FS 1")
        print(f"\033[91mFS NOT FOUND: {active_fs_name}\033[0m")
    else:
        use_macro = FS_NAME_TO_MACRO.get(active_fs_name, "USE_CUSTOM_FS")
        lines.append(f"#define {use_macro} 1")
    lines.append("")

    # FS type selection block
    lines.append("//FatFs port?")
    lines.append("#if defined(USE_FATFS)")
    lines.append("   #include \"fs_port_fatfs.h\"")
    lines.append("//littleFS port?")
    lines.append("#elif defined(USE_LITTLEFS)")
    lines.append("   #include \"fs_port_littlefs.h\"")
    lines.append("//FlashFS port?")
    lines.append("#elif defined(USE_FLASHFS)")
    lines.append("   #include \"fs_port_flashFS.h\"")
    lines.append("//FlashLink port?")
    lines.append("#elif defined(USE_FLASHLINK)")
    lines.append("   #include \"fs_port_flashLink.h\"")
    lines.append("//PC Simulator / Windows / POSIX (JSON: pc_simulator veya _WIN32/__linux__)")
    lines.append("#elif defined(USE_PC_SIMULATOR)") #|| defined(_WIN32) || defined(__linux__) || defined(__FreeBSD__)")
    lines.append("   #include \"fs_port_posix.h\"")
    lines.append("//Custom port?")
    lines.append("#elif defined(USE_CUSTOM_FS)")
    lines.append("   #include \"fs_port_custom.h\"")
    lines.append("//FS not found in fsLib (activeFsName not in fsLib)")
    lines.append("#elif defined(USE_NOT_FOUND_FS)")
    lines.append("   #error \"USE_NOT_FOUND_FS fs is not found\"")
    lines.append("//FS not used (useStore=false)")
    lines.append("#elif defined(USE_NOT_USED_FS)")
    lines.append("   #error \"USE_NOT_USED_FS fs is not used\"")
    lines.append("#endif")
    lines.append("")

    # MACRO DEFINITIONS - only when fs is valid and flashlink
    if use_store and fs_config is not None and active_fs_name == "flashlink":
        _append_flashlink_defines(lines, fs_config)
    else:
        lines.append("/******************************MACRO DEFINITIONS*******************************/")
        lines.append("")

    lines.append("#endif /* __FS_PORT_CONFIG_H__ */")
    lines.append("")
    return "\n".join(lines)


def _append_flashlink_defines(lines: list, fs: dict) -> None:
    """Append FlashLink-specific defines from fs config."""
    cells = fs.get("cells", {})
    flash = fs.get("flash", {})
    hw_func = fs.get("flashHwFunc", {})

    cell_size = int(cells.get("cellSize", 196))
    name_size = int(cells.get("nameSize", 64))
    cell_data_size = int(cells.get("cellDataSize", 128))
    cell_count = int(cells.get("cellCount", 0))

    base_addr = flash.get("baseAddr", "0x00000000")
    if isinstance(base_addr, int):
        base_addr = f"0x{base_addr:08X}"
    region_size = parse_size_to_bytes(flash.get("regionSize", 0))
    erase_block_size = int(flash.get("eraseBlockSize", 0))

    read_func = hw_func.get("readFunc", "Storage_FlashRead")
    write_func = hw_func.get("writeFunc", "Storage_FlashProg")
    erase_func = hw_func.get("eraseFunc", "Storage_FlashErase")
    sync_func = hw_func.get("syncFunc", "Storage_FlashSync")

    lines.append("")
    lines.append("/******************************MACRO DEFINITIONS*******************************/")
    lines.append(f"#define FLASHLINK_CELL_SIZE       ({cell_size})")
    lines.append(f"#define FLASHLINK_NAME_SIZE       ({name_size})")
    lines.append(f"#define FLASHLINK_CELL_DATA_SIZE  ({cell_data_size})")
    lines.append(f"#define FLASHLINK_CELL_COUNT      ({cell_count})")
    lines.append("")
    lines.append(f"#define FLASHLINK_BASE_ADDR        ({base_addr})")
    lines.append(f"#define FLASHLINK_REGION_SIZE      ({region_size})")
    lines.append(f"#define FLASHLINK_ERASE_BLOCK_SIZE ({erase_block_size})")
    lines.append("")
    lines.append(f"#define STORAGE_DRV_FUNC_READ    {read_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_PROG    {write_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_ERASE   {erase_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_SYNC    {sync_func}")
    lines.append("")


def main():
    parser = argparse.ArgumentParser(
        description="Generate fs_port_config.h from customer's fs_config.json.",
        epilog="""
Examples:
  %(prog)s --customer ZD_0101
    Reads  Customers/ZD_0101/Fs/fs_config.json
    Writes Customers/ZD_0101/Fs/fs_port_config.h

  %(prog)s -h
    Show this help message.
""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--customer",
        required=True,
        metavar="NAME",
        help="Customer name (e.g. ZD_0101). Resolves to Customers/<customer>/Fs/fs_config.json",
    )
    parser.add_argument(
        "--script-dir",
        default=None,
        metavar="DIR",
        help="Directory containing this script (default: auto-detect from script location)",
    )
    args = parser.parse_args()

    script_path = os.path.realpath(__file__)
    script_dir = os.path.dirname(script_path)
    if args.script_dir:
        script_dir = os.path.realpath(args.script_dir)

    customers_root = script_dir
    json_path = os.path.join(customers_root, args.customer, "Fs", "fs_config.json")
    out_path = os.path.join(customers_root, args.customer, "Fs", "fs_port_config.h")

    if not os.path.isfile(json_path):
        print(f"Error: Config file not found: {json_path}", file=sys.stderr)
        sys.exit(1)

    with open(json_path, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    script_name = os.path.basename(__file__)
    text = generate_header(cfg, args.customer, script_name)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
