#!/usr/bin/env python3
"""
Network Service Configuration Code Generator

Reads:  Customers/<customer>/Network/network_config.json
Writes: Customers/<customer>/Network/Cus_Network_Config.h
        Customers/<customer>/Network/Cus_Network_Config.c
        Customers/NetworkService_Config.h

Rules:
- First networkStack entry with use: true is the active stack (others ignored).
- Under interfaces, only ethInterfaces / gsmInterfaces arrays; entries with use: true are active.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any


APP_PREFIX = "Application/AppZMeterGw/"


def _c_bool(b: bool) -> str:
    return "true" if b else "false"


def _c_str(s: Any) -> str:
    if s is None:
        return "NULL"
    t = str(s).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{t}"'


def _c_str_path(s: str) -> str:
    """String macro for paths (quoted)."""
    return _c_str(s)


def _first_active_stack(network_stack: list[dict[str, Any]]) -> dict[str, Any] | None:
    for st in network_stack:
        if isinstance(st, dict) and st.get("use") is True:
            return st
    return None


def _collect_active_interfaces(
    interfaces: dict[str, Any],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Return (active_eth_list, active_gsm_list) in array order."""
    active_eth: list[dict[str, Any]] = []
    active_gsm: list[dict[str, Any]] = []

    for item in interfaces.get("ethInterfaces") or []:
        if isinstance(item, dict) and item.get("use") is True:
            active_eth.append(item)

    for item in interfaces.get("gsmInterfaces") or []:
        if isinstance(item, dict) and item.get("use") is True:
            active_gsm.append(item)

    return active_eth, active_gsm

def _stack_path_define(stack_path: str | None) -> str:
    if not stack_path:
        return _c_str("")
    return _c_str(stack_path.rstrip("/") + "/")


def _dns_list(dns: dict[str, Any] | None) -> str:
    if not dns:
        return "8.8.8.8,8.8.4.4"
    lst = dns.get("dnsServerList") or []
    return ",".join(str(x) for x in lst) if lst else ""


def _eth_macro_prefix(n_eth: int, idx: int) -> str:
    if n_eth <= 1:
        return "ETH"
    return f"ETH{idx}"


def _ppp_macro_prefix(n_gsm: int, idx: int) -> str:
    if n_gsm <= 1:
        return "PPP"
    return f"PPP{idx}"


def generate_cus_network_config_h(
    cfg: dict[str, Any],
    customer: str,
) -> str:
    stacks = cfg.get("networkStack") or []
    if not isinstance(stacks, list):
        stacks = []

    stack = _first_active_stack(stacks)
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: list[str] = [
        "/******************************************************************************",
        "* designed by   : Zafer Satilmis",
        "* hype-man      : EPICA - Cry for the Moon",
        f"* customer      : {customer}",
        "* generated by  : generate_network_service.py",
        f"* generated on  : {now}",
        "******************************************************************************/",
        "/******************************************************************************",
        "* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"* Customer Name: {customer}",
        "* Generated from customer network_config.json via generate_network_service.py.",
        "******************************************************************************/",
        "#ifndef __CUS_NETWORK_CONFIG_H__",
        "#define __CUS_NETWORK_CONFIG_H__",
        "",
    ]

    if stack is None:
        lines += [
            "/* No networkStack with use: true — minimal placeholders */",
            "#define NET_INTERFACE_COUNT     (0)",
            "#define NET_STACK_NAME            \"NONE\"",
            "#define NET_STACK_VERSION         \"0\"",
            "",
            "#endif /* __CUS_NETWORK_CONFIG_H__ */",
            "",
        ]
        return "\n".join(lines)

    interfaces = stack.get("interfaces") or {}
    if not isinstance(interfaces, dict):
        interfaces = {}

    active_eth, active_gsm = _collect_active_interfaces(interfaces)
    net_count = len(active_eth) + len(active_gsm)

    name = str(stack.get("name", "Unknown"))
    version = str(stack.get("version", "0"))

    lines.append("")
    lines.append(f"#define NET_INTERFACE_COUNT     ({net_count})")
    lines.append(f'#define NET_STACK_NAME          "{name}"')
    lines.append(f'#define NET_STACK_VERSION       "{version}"')
    lines.append(f"#define NET_STACK_CONFIG_FILE   {_stack_path_define(stack.get('configFilePath'))}")
    lines.append(f"#define NET_STACK_STACK_PATH    {_stack_path_define(stack.get('stackPath'))}")
    lines.append("")

    init_src = stack.get("stackInitSourcePath")
    init_fn = stack.get("stackInitFunction")
    if init_src:
        lines.append(f'#include "{init_src}"')
    if init_fn:
        lines.append(f"#define NET_STACK_STACK_INIT_FUNCTION       ({init_fn})")
    else:
        lines.append("/* NET_STACK_STACK_INIT_FUNCTION not defined — no stackInitFunction in JSON */")

    lines.append("")
    lines.append(f"#define NET_STACK_DHCP_CLIENT   {_c_bool(bool(stack.get('dhcpClient')))}")
    lines.append(f"#define NET_STACK_DHCP_SERVER   {_c_bool(bool(stack.get('dhcpServer')))}")

    dns = stack.get("dns") or {}
    if isinstance(dns, dict):
        dns_use = bool(dns.get("use"))
        lines.append(f"#define NET_STACK_DNS_USE       {_c_bool(dns_use)}")
        lines.append(f'#define NET_STACK_DNS_SERVER_LIST "{_dns_list(dns)}"')
    else:
        lines.append("#define NET_STACK_DNS_USE       false")
        lines.append('#define NET_STACK_DNS_SERVER_LIST "8.8.8.8,8.8.4.4"')

    n_eth = len(active_eth)
    n_gsm = len(active_gsm)

    # Global interface index for numbering (eth first, then PPP)
    gidx = 0

    # --- Ethernet blocks ---
    for i, eth in enumerate(active_eth):
        prefix = _eth_macro_prefix(n_eth, i)
        lines.append("")
        lines.append("/****** Ethernet Interface Configuration **************************************/")
        eth_path = eth.get("ethAppManagerPath") or eth.get("appManager")
        if eth_path:
            lines.append(f'#include "{eth_path}"')

        sf = eth.get("ethAppManagerStartFunction")
        cf = eth.get("ethAppManagerCloseFunction")
        rf = eth.get("ethAppManagerReconnectFunction")
        wf = eth.get("ethAppManagerIsNetworkReadyFunction")
        if sf:
            lines.append(f"#define {prefix}_APP_MANAGER_START_FUNCTION            ({sf})")
        if cf:
            lines.append(f"#define {prefix}_APP_MANAGER_CLOSE_FUNCTION            ({cf})")
        if rf:
            lines.append(f"#define {prefix}_APP_MANAGER_RECONNECT_FUNCTION        ({rf})")
        if wf:
            lines.append(f"#define {prefix}_APP_MANAGER_IS_NETWORK_READY_FUNCTION ({wf})")

        lines.append("")
        lines.append(f"#define {prefix}_INTERFACE_NUMBER        ({gidx})")
        gidx += 1

        if eth.get("ifname"):
            lines.append(f'#define {prefix}_IF_NAME                 "{eth["ifname"]}"')
        if eth.get("hostname"):
            lines.append(f'#define {prefix}_HOST_NAME               "{eth["hostname"]}"')
        if eth.get("macAddr"):
            lines.append(f'#define {prefix}_MAC_ADDR                "{eth["macAddr"]}"')
        if eth.get("ipAddr") is not None:
            lines.append(f'#define {prefix}_IP_ADDR                 "{eth["ipAddr"]}"')
        if eth.get("subnetMask"):
            lines.append(f'#define {prefix}_SUBNET_MASK             "{eth["subnetMask"]}"')
        if eth.get("defaultGateway"):
            lines.append(f'#define {prefix}_DEFAULT_GATEWAY         "{eth["defaultGateway"]}"')

        nic = eth.get("nicDriver") or {}
        if isinstance(nic, dict):
            dc = nic.get("driverConfig") or {}
            if isinstance(dc, dict):
                if dc.get("spiDriver"):
                    lines.append(f"#define {prefix}_DRIVER_SPI_DRIVER           {dc['spiDriver']}")
                if dc.get("spiLine"):
                    lines.append(f"#define {prefix}_DRIVER_SPI_LINE             {dc['spiLine']}")
                if dc.get("spiDriverPath"):
                    lines.append(f'#define {prefix}_DRIVER_SPI_DRIVER_PATH      "{dc["spiDriverPath"]}"')
                if dc.get("extIntDriver"):
                    lines.append(f"#define {prefix}_DRIVER_EXT_INT_DRIVER       {dc['extIntDriver']}")
                if dc.get("extIntLine"):
                    lines.append(f"#define {prefix}_DRIVER_EXT_INT_LINE         {dc['extIntLine']}")
                if dc.get("extIntDriverPath"):
                    lines.append(f'#define {prefix}_DRIVER_EXT_INT_DRIVER_PATH  "{dc["extIntDriverPath"]}"')

    # --- PPP / GSM blocks ---
    for i, gsm in enumerate(active_gsm):
        prefix = _ppp_macro_prefix(n_gsm, i)
        lines.append("")
        lines.append("/****** PPP Interface Configuration ******************************************/")
        pp_path = gsm.get("ppAppManagerPath") or gsm.get("appManager")
        if pp_path:
            lines.append(f'#include "{pp_path}"')

        sf = gsm.get("ppAppManagerStartFunction")
        cf = gsm.get("ppAppManagerCloseFunction")
        rf = gsm.get("ppAppManagerReconnectFunction")
        wf = gsm.get("ppAppManagerIsNetworkReadyFunction")
        if sf:
            lines.append(f"#define {prefix}_APP_MANAGER_START_FUNCTION            ({sf})")
        if cf:
            lines.append(f"#define {prefix}_APP_MANAGER_CLOSE_FUNCTION            ({cf})")
        if rf:
            lines.append(f"#define {prefix}_APP_MANAGER_RECONNECT_FUNCTION        ({rf})")
        if wf:
            lines.append(f"#define {prefix}_APP_MANAGER_IS_NETWORK_READY_FUNCTION ({wf})")

        lines.append("")
        lines.append(f"#define {prefix}_INTERFACE_NUMBER     ({gidx})")
        gidx += 1

        if gsm.get("ifname"):
            lines.append(f'#define {prefix}_IF_NAME              "{gsm["ifname"]}"')

        gmc = gsm.get("gsmModemConfig") or {}
        if isinstance(gmc, dict):
            pc = gmc.get("pinCode")
            lines.append(f"#define {prefix}_APP_PIN_CODE          {_c_str(pc) if pc is not None else 'NULL'}")
            if gmc.get("apn") is not None:
                lines.append(f'#define {prefix}_APP_APN               "{gmc["apn"]}"')
            if gmc.get("phoneNumber") is not None:
                lines.append(f'#define {prefix}_APP_PHONE_NUMBER      "{gmc["phoneNumber"]}"')
            if gmc.get("timeout") is not None:
                lines.append(f"#define {prefix}_APP_TIMEOUT           {int(gmc['timeout'])}")

        drv = gsm.get("driverConfig") or {}
        if isinstance(drv, dict):
            if drv.get("uartLine"):
                lines.append(f"#define {prefix}_APP_UART_LINE         {drv['uartLine']}")
            if drv.get("uartDriverPath"):
                lines.append(f'#define {prefix}_APP_UART_DRIVER_PATH  "{drv["uartDriverPath"]}"')

    lines.append("")
    lines.append("#endif /* __CUS_NETWORK_CONFIG_H__ */")
    lines.append("")
    lines.append("/******************************** End Of File *********************************/")
    return "\n".join(lines)


def _eth_start_macro(n_eth: int, idx: int) -> str:
    if n_eth <= 1:
        return "ETH_APP_MANAGER_START_FUNCTION"
    return f"ETH{idx}_APP_MANAGER_START_FUNCTION"


def _ppp_start_macro(n_gsm: int, idx: int) -> str:
    if n_gsm <= 1:
        return "PPP_APP_MANAGER_START_FUNCTION"
    return f"PPP{idx}_APP_MANAGER_START_FUNCTION"


def generate_cus_network_config_c(
    cfg: dict[str, Any],
    customer: str,
) -> str:
    stacks = cfg.get("networkStack") or []
    stack = _first_active_stack(stacks) if isinstance(stacks, list) else None
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header = "\n".join(
        [
            "/******************************************************************************",
            "* #Author       : Auto-generated",
            "* hype-man      : EPICA - Kingdom of Heaven",
            "* #File Name    : Cus_Network_Config.c",
            f"* #Customer     : {customer}",
            f"* #Date         : {now}",
            "******************************************************************************/",
            "/******************************************************************************",
            "* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
            f"* Customer Name: {customer}",
            "* Generated from customer network_config.json via generate_network_service.py.",
            "******************************************************************************/",
            "",
            "#define SHOW_PAGE_DBG_MSG  (DISABLE)",
            "/********************************* INCLUDES ***********************************/",
            '#include "Cus_Network_Config.h"',
            '#include "Project_Conf.h"',
            "",
            "/****************************** MACRO DEFINITIONS *****************************/",
            "",
            "/******************************* TYPE DEFINITIONS *****************************/",
            "",
            "/********************************** VARIABLES *********************************/",
            "",
            "",
            "/***************************** STATIC FUNCTIONS *******************************/",
            "",
            "/***************************** PUBLIC FUNCTIONS *******************************/",
            "",
        ]
    )

    if stack is None:
        body = "\n".join(
            [
                "RETURN_STATUS networkServiceInitTCPIPStack(void)",
                "{",
                "    return SUCCESS;",
                "}",
                "",
                "RETURN_STATUS networkServiceStartInterfaces(void)",
                "{",
                "    return SUCCESS;",
                "}",
                "",
            ]
        )
        return header + body + "\n/******************************** End Of File *********************************/\n"

    interfaces = stack.get("interfaces") or {}
    if not isinstance(interfaces, dict):
        interfaces = {}

    active_eth, active_gsm = _collect_active_interfaces(interfaces)
    n_eth = len(active_eth)
    n_gsm = len(active_gsm)

    init_fn = stack.get("stackInitFunction")
    if init_fn:
        init_body = f"    return NET_STACK_STACK_INIT_FUNCTION();"
    else:
        init_body = "    return SUCCESS;"

    start_lines = ["    RETURN_STATUS retVal = SUCCESS;"]
    for i in range(n_eth):
        sm = _eth_start_macro(n_eth, i)
        start_lines.append(f"    retVal |= {sm}();")
    for i in range(n_gsm):
        sm = _ppp_start_macro(n_gsm, i)
        start_lines.append(f"    retVal |= {sm}();")
    start_lines.append("    return retVal;")

    if n_eth == 0 and n_gsm == 0:
        start_lines = ["    (void)0;", "    return SUCCESS;"]

    body = "\n".join(
        [
            "RETURN_STATUS networkServiceInitTCPIPStack(void)",
            "{",
            init_body,
            "}",
            "",
            "RETURN_STATUS networkServiceStartInterfaces(void)",
            "{",
            *start_lines,
            "}",
            "",
        ]
    )

    return header + body + "\n/******************************** End Of File *********************************/\n"


def generate_network_service_config_h(customer: str) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return "\n".join(
        [
            "/**",
            " * @file NetworkService_Config.h",
            " * @brief AUTO-GENERATED configuration for Network Service",
            " *        AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
            " */",
            "#ifndef __APP_NETWORK_SERVICE_CONFIG_H__",
            "#define __APP_NETWORK_SERVICE_CONFIG_H__",
            "",
            f"/* generated on: {now} */",
            f"/* customer name: {customer} */",
            "",
            f'#include "{customer}/Network/Cus_Network_Config.h"',
            "",
            "",
            "#endif /* __APP_NETWORK_SERVICE_CONFIG_H__ */",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Network Cus headers and NetworkService_Config.h from network_config.json"
    )
    parser.add_argument(
        "--customer",
        required=True,
        help="Customer folder under Customers/ (e.g. LinuxGcc)",
    )
    args = parser.parse_args()

    here = Path(__file__).resolve().parent
    json_path = here / args.customer / "Network" / "network_config.json"
    if not json_path.exists():
        raise SystemExit(f"Config not found: {json_path}")

    cfg = json.loads(json_path.read_text(encoding="utf-8"))

    out_h = here / args.customer / "Network" / "Cus_Network_Config.h"
    out_c = here / args.customer / "Network" / "Cus_Network_Config.c"
    out_root = here / "NetworkService_Config.h"

    out_h.parent.mkdir(parents=True, exist_ok=True)
    here.mkdir(parents=True, exist_ok=True)

    out_h.write_text(generate_cus_network_config_h(cfg, args.customer), encoding="utf-8")
    out_c.write_text(generate_cus_network_config_c(cfg, args.customer), encoding="utf-8")
    out_root.write_text(generate_network_service_config_h(args.customer), encoding="utf-8")

    print(f"Generated: {out_h}")
    print(f"Generated: {out_c}")
    print(f"Generated: {out_root}")


if __name__ == "__main__":
    main()
