#!/usr/bin/env python3
"""
Logger Service Configuration Code Generator

Reads:
  Customers/<customer>/Logger/logger_config.json

Generates:
  Customers/<customer>/Logger/Cus_LoggerService_Config.h
  Customers/Cus_LoggerService_Conf.h
  Customers/<customer>/Logger/Cus_LoggerService_Conf.c
  Customers/LoggerService_Config.h

Important:
  - If a logger entry in loggerList has "use": false, that logger's code is NOT generated.
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path


def _c_bool(x: bool) -> str:
    return "TRUE" if x else "FALSE"


def _c_enable(x: bool) -> str:
    return "ENABLE" if x else "DISABLE"


def _abbr_from_logger_name(name: str) -> tuple[str, str]:
    """
    Returns (abbrUpper, abbrLower) used for:
      - LOGGER_<ABBR>_* macro prefixes
      - global variable names g_<abbrLower>LoggerID

    Heuristic:
      - Strip trailing 'Logger' (case-insensitive)
      - Use first 4 chars if length >= 4, else first 3 chars.
    """
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "", name).strip()
    base = re.sub(r"Logger$", "", cleaned, flags=re.IGNORECASE)
    base_lower = base.lower()
    if not base_lower:
        base_lower = cleaned.lower()
    if len(base_lower) >= 4:
        abbr_lower = base_lower[:4]
    else:
        abbr_lower = base_lower[:3]
    abbr_upper = abbr_lower.upper()
    return abbr_upper, abbr_lower


def _logger_var_name(abbr_lower: str) -> str:
    return f"g_{abbr_lower}LoggerID"


def _logger_conf_var_name(logger_name: str) -> str:
    # e.g. sysLogger -> sysLoggerConf
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "", logger_name)
    return f"{cleaned}Conf"


def _logger_char_name(abbr_lower: str) -> str:
    # e.g. sys -> loggerSysName
    cap = abbr_lower[:1].upper() + abbr_lower[1:]
    return f"logger{cap}Name"


def generate_logger_service(customer: str, repo_root: Path) -> None:
    here = repo_root / "Customers"
    customer_dir = here / customer / "Logger"
    json_path = customer_dir / "logger_config.json"
    if not json_path.exists():
        raise SystemExit(f"Config not found: {json_path}")

    cfg = json.loads(json_path.read_text(encoding="utf-8"))
    logger_service = cfg.get("loggerService", {})

    service_use = bool(logger_service.get("use", True))
    queue_size = int(logger_service.get("queueSize", 10))
    log_max_length = int(logger_service.get("logMaxLength", 128))

    logger_list = logger_service.get("loggerList", [])
    # Filter active loggers by BOTH overall service use and per-logger use flag.
    active_loggers = []
    if service_use:
        for item in logger_list:
            if bool(item.get("use", True)):
                active_loggers.append(item)

    active_count = len(active_loggers)
    has_any_logger = service_use and active_count > 0
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # -------------------- Cus_LoggerService_Config.h --------------------
    lines_cfg_h: list[str] = []
    lines_cfg_h += [
        "/******************************************************************************",
        "* designed by   : Zafer Satilmis",
        "* hype-man      : Sexen - Stolen Chastity",
        f"* customer      : {customer}",
        "* generated by  : generate_logger_service.py",
        f"* generated on  : {now}",
        "******************************************************************************/",
        "/******************************************************************************",
        "* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"* Customer Name: {customer}",
        "* Generated from customer logger_config.json via generate_logger_service.py.",
        "******************************************************************************/",
        f"#ifndef __CUS_LOGGER_SERVICE_CONFIG_H__",
        f"#define __CUS_LOGGER_SERVICE_CONFIG_H__",
        "/*********************************INCLUDES*************************************/",
        "#include \"Project_Conf.h\"",
        "",
        "/************************* GLOBAL VARIBALE REFERENCES *************************/",
    ]

    for logger in active_loggers:
        abbr_upper, abbr_lower = _abbr_from_logger_name(str(logger["name"]))
        lines_cfg_h.append(f"/* {logger['name']} */")
        lines_cfg_h.append(f"extern S32 {_logger_var_name(abbr_lower)};")
    if not active_loggers:
        lines_cfg_h.append("/* No active loggers */")

    lines_cfg_h += [
        "/****************************** MACRO DEFINITIONS *******************************/",
        f"#define USE_LOGGER_SERVICE ({_c_enable(service_use)})",
        "",
        f"#define LOGGER_QUEUE_SIZE     ({queue_size})",
        f"#define LOGGER_LOG_MAX_LENGTH ({log_max_length})",
        "",
        "/****** Loggers List *****/",
        f"#define ACTIVE_LOGGER_COUNT ({active_count})",
        "",
    ]

    # Logging macro:
    # - If at least one logger is active, calls the real recorder.
    # - If logger service is disabled or no logger is active, the macro expands to nothing.
    if has_any_logger:
        lines_cfg_h.append("#define APP_LOG_REC(logID, str) appLogRec(logID, str);")
    else:
        lines_cfg_h.append("#define APP_LOG_REC(logID, str)")

    # For each active logger, generate macros.
    for idx, logger in enumerate(active_loggers, start=1):
        name = str(logger["name"])
        abbr_upper, abbr_lower = _abbr_from_logger_name(name)

        fs_path = str(logger["fsPath"])
        open_func = str(logger["openFunc"])
        read_func = str(logger["readFunc"])
        write_func = str(logger["writeFunc"])
        close_func = str(logger["closeFunc"])
        log_path = str(logger["logPath"])
        file_size = int(logger["fileSize"])
        total_log_size = int(logger["totalLogSize"])

        time_info = logger.get("timeInfo", {}) or {}
        time_use = bool(time_info.get("use", False))
        time_format = str(time_info.get("format", "FIRST_YEAR"))

        lines_cfg_h += [
            f"/** logger-{idx} {name} configuration **/",
            f"#define LOGGER_{abbr_upper}_NAME               \"{name}\"",
            f"#define LOGGER_{abbr_upper}_USE                ({_c_bool(True)})",
            f"#define LOGGER_{abbr_upper}_FS_PATH            \"{fs_path}\"",
            f"#define LOGGER_{abbr_upper}_OPEN_FUNC          ({open_func})",
            f"#define LOGGER_{abbr_upper}_READ_FUNC          ({read_func})",
            f"#define LOGGER_{abbr_upper}_WRITE_FUNC         ({write_func})",
            f"#define LOGGER_{abbr_upper}_CLOSE_FUNC         ({close_func})",
            f"#define LOGGER_{abbr_upper}_LOG_PATH           \"{log_path}\"",
            f"#define LOGGER_{abbr_upper}_FILE_SIZE          ({file_size})",
            f"#define LOGGER_{abbr_upper}_TOTAL_LOG_SIZE     ({total_log_size})",
            f"#define LOGGER_{abbr_upper}_TIME_INFO_USE      ({_c_bool(time_use)})",
            f"#define LOGGER_{abbr_upper}_TIME_INFO_FORMAT   ({time_format})",
            "",
        ]

    # Keep the legacy function prototype in this header.
    lines_cfg_h += [
        "/************************* GLOBAL FUNCTION DEFINITIONS ************************/",
        "RETURN_STATUS appLogStartLoggers(void);",
        "",
        f"#endif /* __CUS_LOGGER_SERVICE_CONFIG_H__ */",
        "",
        "/********************************* End Of File ********************************/",
    ]

    out_cfg_h = customer_dir / "Cus_LoggerService_Conf.h"
    out_cfg_h.parent.mkdir(parents=True, exist_ok=True)
    out_cfg_h.write_text("\n".join(lines_cfg_h).rstrip() + "\n", encoding="utf-8")

    # -------------------- Cus_LoggerService_Conf.h --------------------
    conf_h_guard = "__LOGGER_SERVICE_CONFIG_H__"
    lines_conf_h: list[str] = [
        "/******************************************************************************",
        "* designed by   : Zafer Satilmis",
        "* hype-man      : Sexen - Stolen Chastity",
        f"* customer      : {customer}",
        "* generated by  : generate_logger_service.py",
        f"* generated on  : {now}",
        "******************************************************************************/",
        "/******************************************************************************",
        "* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"* Customer Name: {customer}",
        "* Generated from customer logger_config.json via generate_logger_service.py.",
        "******************************************************************************/",
        f"#ifndef {conf_h_guard}",
        f"#define {conf_h_guard}",
        "",
        f"#include \"{customer}/Logger/Cus_LoggerService_Conf.h\"",
        "",
        f"RETURN_STATUS appLogStartLoggers(void);",
        "",
        f"#endif /* {conf_h_guard} */",
        "",
        "/********************************* End Of File ********************************/",
    ]
    out_conf_h = here / "LoggerService_Config.h"
    out_conf_h.write_text("\n".join(lines_conf_h).rstrip() + "\n", encoding="utf-8")

    # -------------------- Cus_LoggerService_Conf.c --------------------
    lines_conf_c: list[str] = []
    lines_conf_c += [
        "/******************************************************************************",
        "* #Author       : Zafer Satilmis",
        "* #File Name    : Cus_LoggerService_Conf.c",
        f"* #Customer     : {customer}",
        f"* #Date         : {now}",
        "******************************************************************************/",
        "/******************************************************************************",
        "* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"* Customer Name: {customer}",
        "* Generated from customer logger_config.json via generate_logger_service.py.",
        "******************************************************************************/",
        "",
        "#define SHOW_PAGE_DBG_MSG  (DISABLE)",
        "/********************************* INCLUDES ***********************************/",
        "#include \"Cus_LoggerService_Conf.h\"",
        "#include \"Project_Conf.h\"",
        "#include \"AppLogRecorder.h\"",
        "",
    ]

    # Include required FS headers only for active loggers.
    for logger in active_loggers:
        name = str(logger["name"])
        abbr_upper, _ = _abbr_from_logger_name(name)
        lines_conf_c.append(f"#include LOGGER_{abbr_upper}_FS_PATH")
    lines_conf_c.append("/****************************** MACRO DEFINITIONS *****************************/")
    lines_conf_c.append("")
    lines_conf_c.append("/******************************* TYPE DEFINITIONS *****************************/")
    lines_conf_c.append("")
    lines_conf_c.append("/********************************** VARIABLES *********************************/")
    lines_conf_c.append("")

    for logger in active_loggers:
        name = str(logger["name"])
        _, abbr_lower = _abbr_from_logger_name(name)
        lines_conf_c.append(f"S32 {_logger_var_name(abbr_lower)};")
    if not active_loggers:
        lines_conf_c.append("/* No active logger variables */")

    lines_conf_c += [
        "",
        "/******************************* PUBLIC FUNCTIONS  *****************************/",
        "",
        "RETURN_STATUS appLogStartLoggers(void)",
        "{",
        "    RETURN_STATUS retVal = SUCCESS;",
        "",
    ]

    # Local variables + registration per active logger
    for logger in active_loggers:
        name = str(logger["name"])
        abbr_upper, abbr_lower = _abbr_from_logger_name(name)
        conf_var = _logger_conf_var_name(name)
        char_var = _logger_char_name(abbr_lower)
        g_id_var = _logger_var_name(abbr_lower)

        lines_conf_c += [
            f"    char {char_var}[] = LOGGER_{abbr_upper}_NAME;",
            "",
            f"    logRecConf_t {conf_var};",
            "",
            f"    {conf_var}.openFunc  = LOGGER_{abbr_upper}_OPEN_FUNC;",
            f"    {conf_var}.writeFunc = LOGGER_{abbr_upper}_WRITE_FUNC;",
            f"    {conf_var}.readFunc  = LOGGER_{abbr_upper}_READ_FUNC;",
            f"    {conf_var}.closeFunc = LOGGER_{abbr_upper}_CLOSE_FUNC;",
            f"    {conf_var}.fileSize  = LOGGER_{abbr_upper}_FILE_SIZE;",
            f"    {conf_var}.logPath   = LOGGER_{abbr_upper}_LOG_PATH;",
            f"    {conf_var}.totalLogSize = LOGGER_{abbr_upper}_TOTAL_LOG_SIZE;",
            f"    {conf_var}.timeStamp = LOGGER_{abbr_upper}_TIME_INFO_USE;",
            f"    {conf_var}.timeStampFormat = LOGGER_{abbr_upper}_TIME_INFO_FORMAT;",
            "",
            f"    retVal |= appLogRecRegister(&{conf_var}, {char_var}, &{g_id_var});",
            "",
        ]

    lines_conf_c += [
        "    return retVal;",
        "}",
        "",
        "/******************************** End Of File *********************************/",
    ]

    out_conf_c = customer_dir / "Cus_LoggerService_Conf.c"
    out_conf_c.write_text("\n".join(lines_conf_c).rstrip() + "\n", encoding="utf-8")

    # -------------------- Customers/LoggerService_Config.h wrapper --------------------
    # Keep same include style as the existing wrapper in the repo.
    lines_wrapper: list[str] = [
        "/******************************************************************************",
        "* designed by   : Zafer Satilmis",
        "* hype-man      : Sexen - Permitted Boots",
        f"* customer      : {customer}",
        "* generated by  : generate_logger_service.py",
        f"* generated on  : {now}",
        "******************************************************************************/",
        "/******************************************************************************",
        "* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"* Customer Name: {customer}",
        "* Generated from customer logger_config.json via generate_logger_service.py.",
        "******************************************************************************/",
        "#ifndef __LOGGER_SERVICE_CONFIG_H__",
        "#define __LOGGER_SERVICE_CONFIG_H__",
        "    /*********************************INCLUDES*************************************/",
        "",
        "/* generated by: generate_logger_service.py */",
        f"/* customer name: {customer} */",
        "",
        f'#include "{customer}/Logger/Cus_LoggerService_Conf.h"',
        "",
        "#endif /* __LOGGER_SERVICE_CONFIG_H__ */",
        "",
        "/********************************* End Of File ********************************/",
    ]
    out_wrapper = here / "LoggerService_Config.h"
    out_wrapper.write_text("\n".join(lines_wrapper).rstrip() + "\n", encoding="utf-8")

    print(f"Generated logger service for customer: {customer}")
    print(f"- {out_cfg_h}")
    print(f"- {out_conf_h}")
    print(f"- {out_conf_c}")
    print(f"- {out_wrapper}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate logger service config from Customers/<customer>/Logger/logger_config.json")
    parser.add_argument("--customer", required=True, help="Customer name (e.g. ZD_0101)")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    generate_logger_service(args.customer, repo_root)


if __name__ == "__main__":
    main()

