#!/usr/bin/env python3
"""
Generate fs_port_config.h from customer's fs_config.json.

Usage:
  python generate_fs_port_config.py --customer ZD_0101
  python generate_fs_port_config.py -h
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

# Map fs name (from activeFsName) -> USE_ macro
FS_NAME_TO_MACRO = {
    "fatfs":       "USE_FATFS",
    "littlefs":    "USE_LITTLEFS",
    "flashfs":     "USE_FLASHFS",
    "flashlink":   "USE_FLASHLINK",
    "pc_simulator": "USE_PC_SIMULATOR",
    "custom":      "USE_CUSTOM_FS",
}

def generate_cus_fs_port_config_h(cfg: dict, customer: str, script_name: str) -> str:
    """Generate fs_port_config.h content."""
    version = cfg.get("version", "0.0")
    release_date = cfg.get("releaseDate", "")
    store = cfg.get("store", {})
    use_store = store.get("useStore", False)
    active_fs_name = store.get("activeFsName", "").strip().lower()
    print(f"\033[92mSELECTED FS NAME: {active_fs_name}\033[0m")
    fs_lib = store.get("fsLib", {})
    fs_config = fs_lib.get(active_fs_name) if active_fs_name else None    

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []
    lines.append("/******************************************************************************")
    lines.append("* designed by  : Zafer Satilmis")
    lines.append("* hype-man     : Judas Priest - Night Crawler")
    lines.append(f"* customer     : {customer}")
    lines.append(f"* version      : {version}")
    lines.append(f"* releaseDate  : {release_date}")
    lines.append(f"* generated by : {script_name}")
    lines.append(f"* generated on : {now_str}")
    lines.append("******************************************************************************/")
    lines.append("/******************************************************************************")
    lines.append("* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY")
    lines.append(f"* Customer Name: {customer}")
    lines.append(f"* Generated from customer fs_config.json. Only used units are included.")
    lines.append("******************************************************************************/")
    
    lines.append("")
    lines.append("#ifndef __CUS_FS_PORT_CONFIG_H__")
    lines.append("#define __CUS_FS_PORT_CONFIG_H__")
    lines.append("")
    lines.append("#ifndef ERROR_NOT_READY")
    lines.append("   #define ERROR_NOT_READY  9999")
    lines.append("#endif")
    lines.append("#ifndef ERROR_ALREADY_EXISTS")
    lines.append("   #define ERROR_ALREADY_EXISTS  9998")
    lines.append("#endif")
    lines.append("")

    if not use_store:
        lines.append("#define USE_NOT_USED_FS 1")
        print(f"\033[91mFS NOT USED\033[0m")
    elif fs_config is None:        
        lines.append("#define USE_NOT_FOUND_FS 1")
        print(f"\033[91mFS NOT FOUND: {active_fs_name}\033[0m")
    else:
        use_macro = FS_NAME_TO_MACRO.get(active_fs_name, "USE_CUSTOM_FS")
        lines.append(f"#define {use_macro} 1")
    lines.append("")

    # FS type selection block
    lines.append("/****************************** INCLUDE FS *******************************/")
    lines.append("//FatFs port?")
    lines.append("#if defined(USE_FATFS)")
    lines.append("   #include \"fs_port_fatfs.h\"")
    lines.append("//littleFS port?")
    lines.append("#elif defined(USE_LITTLEFS)")
    lines.append("   #include \"fs_port_littlefs.h\"")
    lines.append("//FlashFS port?")
    lines.append("#elif defined(USE_FLASHFS)")
    lines.append("   #include \"fs_port_flashFS.h\"")
    lines.append("//FlashLink port?")
    lines.append("#elif defined(USE_FLASHLINK)")
    lines.append("   #include \"fs_port_flashLink.h\"")
    lines.append("//PC Simulator / Windows / POSIX (JSON: pc_simulator veya _WIN32/__linux__)")
    lines.append("#elif defined(USE_PC_SIMULATOR)") #|| defined(_WIN32) || defined(__linux__) || defined(__FreeBSD__)")
    lines.append("   #include \"fs_port_posix.h\"")
    lines.append("//Custom port?")
    lines.append("#elif defined(USE_CUSTOM_FS)")
    lines.append("   #include \"fs_port_custom.h\"")
    lines.append("//FS not found in fsLib (activeFsName not in fsLib)")
    lines.append("#elif defined(USE_NOT_FOUND_FS)")
    lines.append("   #error \"USE_NOT_FOUND_FS fs is not found\"")
    lines.append("//FS not used (useStore=false)")
    lines.append("#elif defined(USE_NOT_USED_FS)")
    lines.append("   #error \"USE_NOT_USED_FS fs is not used\"")
    lines.append("#endif")
    lines.append("")

    # MACRO DEFINITIONS - only when fs is valid and flashlink
    if use_store and fs_config is not None and active_fs_name == "flashlink":
        _append_flashlink_defines(lines, fs_config)
    elif use_store and fs_config is not None and active_fs_name == "fatfs":
        _append_fatfs_defines(lines, fs_config)
    elif use_store and fs_config is not None and active_fs_name == "littlefs":
        _append_littlefs_defines(lines, fs_config)
    elif use_store and fs_config is not None and active_fs_name == "flashfs":
        _append_flashfs_defines(lines, fs_config)
    elif use_store and fs_config is not None and active_fs_name == "pc_simulator":
        _append_pc_simulator_defines(lines, fs_config)
    elif use_store and fs_config is not None and active_fs_name == "custom":        
        print(f"\033[91mFS NOT FOUND: {active_fs_name}\033[0m")
    else:
        lines.append("/****************************** MACRO DEFINITIONS *******************************/")
        lines.append("")    

    

    lines.append("#endif /* __CUS_FS_PORT_CONFIG_H__ */")
    lines.append("")
    return "\n".join(lines)


def _append_flashlink_defines(lines: list, fs: dict) -> None:
    """Append FlashLink-specific defines from fs config."""

    flash = fs.get("flash", {})
    cells = flash.get("cells", {})
    cell_size = int(cells.get("cellSize", 0))
    name_size = int(cells.get("nameSize", 0))
    cell_data_size = int(cells.get("cellDataSize", 0))
    cell_count = int(cells.get("cellCount", 0))

    flash = flash.get("geometry", {})
    base_addr = flash.get("baseAddr", "0x00000000")
    if isinstance(base_addr, int):
        base_addr = f"0x{base_addr:08X}"
    region_size = int(flash.get("regionSize", 0))
    erase_block_size = int(flash.get("eraseBlockSize", 0))

    hw_func = fs.get("flashHwFunc", {})
    drv_src_path = hw_func.get("drvSrcPath", "")
    read_func = hw_func.get("readFunc", "NOT_FOUND_FUNC");
    write_func = hw_func.get("writeFunc", "NOT_FOUND_FUNC");
    erase_func = hw_func.get("eraseFunc", "NOT_FOUND_FUNC");
    sync_func = hw_func.get("syncFunc", "NOT_FOUND_FUNC");   

    print(f"--------------------------------")
    print(f"\033[96mcell_size: \033[0m{cell_size}")
    print(f"\033[96mname_size: \033[0m{name_size}")
    print(f"\033[96mcell_data_size: \033[0m{cell_data_size}")
    print(f"\033[96mcell_count: \033[0m{cell_count}")
    print(f"\033[96mbase_addr: \033[0m{base_addr}")
    print(f"\033[96mregion_size: \033[0m{region_size}")
    print(f"\033[96merase_block_size: \033[0m{erase_block_size}")
    print(f"\033[96mdrv_src_path: \033[0m{drv_src_path}")
    print(f"\033[96mread_func: \033[0m{read_func}")
    print(f"\033[96mwrite_func: \033[0m{write_func}")
    print(f"\033[96merase_func: \033[0m{erase_func}")
    print(f"\033[96msync_func: \033[0m{sync_func}")
    print(f"--------------------------------")

    lines.append("/****************************** HW DRIVER INCLUDE *******************************/")
    lines.append(f"#include \"{drv_src_path}\"")
    lines.append("")
    lines.append("/****************************** MACRO DEFINITIONS *******************************/")
    lines.append(f"#define FLASHLINK_CELL_SIZE       ({cell_size})")
    lines.append(f"#define FLASHLINK_NAME_SIZE       ({name_size})")
    lines.append(f"#define FLASHLINK_CELL_DATA_SIZE  ({cell_data_size})")
    lines.append(f"#define FLASHLINK_CELL_COUNT      ({cell_count})")
    lines.append("")
    lines.append(f"#define FLASHLINK_BASE_ADDR        ({base_addr})")
    lines.append(f"#define FLASHLINK_REGION_SIZE      ({region_size})")
    lines.append(f"#define FLASHLINK_ERASE_BLOCK_SIZE ({erase_block_size})")
    lines.append("")
    lines.append(f"#define STORAGE_DRV_FUNC_READ    {read_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_PROG    {write_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_ERASE   {erase_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_SYNC    {sync_func}")
    lines.append("")

    lines.append(
        """#define FS_HARDWARE_INIT(error_out) \\                   
                    do { \\                        
                        FlashLinkOps ops = { \\
                            .read = STORAGE_DRV_FUNC_READ, \\
                            .prog = STORAGE_DRV_FUNC_PROG, \\
                            .erase = STORAGE_DRV_FUNC_ERASE, \\
                            .sync = STORAGE_DRV_FUNC_SYNC \\
                        }; \\
                        
                        FlashLinkConfig cfg = { \\
                            .baseAddr = FLASHLINK_BASE_ADDR, \\
                            .regionSize = FLASHLINK_REGION_SIZE, \\
                            .cellCount = FLASHLINK_CELL_COUNT, \\
                            .eraseBlockSize = FLASHLINK_ERASE_BLOCK_SIZE \\
                        }; \\
                        
                        error_out = flashLinkInit(&ops, &cfg); \\
                        if(NO_ERROR == error_out) \\
                        { \\
                            error_out = flashLinkFormat(); \\ 
                        }\\
                                               
                    } while (0)"""
    )

def _append_fatfs_defines(lines: list, fs: dict) -> None:
    """Append fatFs-specific defines from fs config."""

    flash = fs.get("flash", {})

    chipName = flash.get("chipName", "")
    capacityBytes = int(flash.get("capacityBytes", 0))

    geometry = flash.get("geometry", {})
    geometry_pageSize = int(geometry.get("pageSize", 0))    
    geometry_sectorSize = int(geometry.get("sectorSize", 0))
    geometry_blockSize = int(geometry.get("blockSize", 0))
    geometry_baseAddr = geometry.get("baseAddr", "0x00000000")
    if isinstance(geometry_baseAddr, int):
        geometry_baseAddr = f"0x{geometry_baseAddr:08X}"

    hw_func = fs.get("flashHwFunc", {})
    drv_src_path = hw_func.get("drvSrcPath", "")
    read_func = hw_func.get("readFunc", "NOT_FOUND_FUNC");
    write_func = hw_func.get("writeFunc", "NOT_FOUND_FUNC");
    erase_func = hw_func.get("eraseFunc", "NOT_FOUND_FUNC");
    sync_func = hw_func.get("syncFunc", "NOT_FOUND_FUNC");

    print(f"--------------------------------")
    print(f"\033[96mchipName: \033[0m{chipName}")
    print(f"\033[96mcapacityBytes: \033[0m{capacityBytes}")
    print(f"\033[96mgeometry_pageSize: \033[0m{geometry_pageSize}")
    print(f"\033[96mgeometry_sectorSize: \033[0m{geometry_sectorSize}")
    print(f"\033[96mgeometry_blockSize: \033[0m{geometry_blockSize}")
    print(f"\033[96mgeometry_baseAddr: \033[0m{geometry_baseAddr}")
    print(f"--------------------------------")
    print(f"\033[96mdrv_src_path: \033[0m{drv_src_path}")
    print(f"\033[96mread_func: \033[0m{read_func}")
    print(f"\033[96mwrite_func: \033[0m{write_func}")
    print(f"\033[96merase_func: \033[0m{erase_func}")
    print(f"\033[96msync_func: \033[0m{sync_func}")    
    print(f"--------------------------------")

    lines.append("/****************************** HW DRIVER INCLUDE *******************************/")
    lines.append(f"#define CHIP_NAME \"{chipName}\"")
    lines.append("")
    lines.append(f"#include \"{drv_src_path}\"")
    lines.append("")
    lines.append("/****************************** MACRO DEFINITIONS *******************************/")
    lines.append(f"#define FATFS_CAPACITY_BYTES     ({capacityBytes})")
    lines.append("")
    lines.append(f"#define FATFS_GEOMETRY_PAGE_SIZE    ({geometry_pageSize})")
    lines.append(f"#define FATFS_GEOMETRY_SECTOR_SIZE  ({geometry_sectorSize})")
    lines.append(f"#define FATFS_GEOMETRY_BLOCK_SIZE   ({geometry_blockSize})")
    lines.append(f"#define FATFS_GEOMETRY_BASE_ADDR    ({geometry_baseAddr})")
    lines.append("")
    lines.append(f"#define STORAGE_DRV_FUNC_READ    {read_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_PROG    {write_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_ERASE   {erase_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_SYNC    {sync_func}")
    lines.append("")
    lines.append(
    """#define FS_HARDWARE_INIT(error_out) \\                   
                do { \\                        
                    error_out = NO_ERROR; \\                                          
                } while (0)"""
    )

def _append_littlefs_defines(lines: list, fs: dict) -> None:
    """Append littleFs-specific defines from fs config."""

    flash = fs.get("flash", {})

    chipName = flash.get("chipName", "")
    capacityBytes = int(flash.get("capacityBytes", 0))

    geometry = flash.get("geometry", {})
    readSize = int(geometry.get("readSize", 0))
    progSize = int(geometry.get("progSize", 0))
    blockSize = int(geometry.get("blockSize", 0))
    blockCount = int(geometry.get("blockCount", 0))
    cacheSize = int(geometry.get("cacheSize", 0))
    lookaheadSize = int(geometry.get("lookaheadSize", 0))
    blockCycles = int(geometry.get("blockCycles", 0))
    nameMax = int(geometry.get("nameMax", 0))
    fileMax = int(geometry.get("fileMax", 0))
    attrMax = int(geometry.get("attrMax", 0))
    baseAddr = geometry.get("baseAddr", "0x00000000")
    if isinstance(baseAddr, int):
        baseAddr = f"0x{baseAddr:08X}"

    os_helper = fs.get("osHelper", {})
    os_helper_path = os_helper.get("path", "")
    mutexCreate = os_helper.get("mutexCreate", "NOT_FOUND_FUNC");
    mutexDelete = os_helper.get("mutexDelete", "NOT_FOUND_FUNC");
    mutexLock = os_helper.get("mutexLock", "NOT_FOUND_FUNC");
    mutexUnlock = os_helper.get("mutexUnlock", "NOT_FOUND_FUNC");

    hw_func = fs.get("flashHwFunc", {})
    drv_src_path = hw_func.get("drvSrcPath", "")
    init_func = hw_func.get("initFunc", "NOT_FOUND_FUNC");
    read_func = hw_func.get("readFunc", "NOT_FOUND_FUNC");
    write_func = hw_func.get("writeFunc", "NOT_FOUND_FUNC");
    erase_func = hw_func.get("eraseFunc", "NOT_FOUND_FUNC");
    sync_func = hw_func.get("syncFunc", "NOT_FOUND_FUNC");

    print(f"--------------------------------")
    print(f"\033[96mchipName: \033[0m{chipName}")
    print(f"\033[96mcapacityBytes: \033[0m{capacityBytes}")
    print(f"--------------------------------")
    print(f"\033[96mreadSize: \033[0m{readSize}")
    print(f"\033[96mprogSize: \033[0m{progSize}")
    print(f"\033[96mblockSize: \033[0m{blockSize}")
    print(f"\033[96mblockCount: \033[0m{blockCount}")
    print(f"\033[96mcacheSize: \033[0m{cacheSize}")
    print(f"\033[96mlookaheadSize: \033[0m{lookaheadSize}")
    print(f"\033[96mblockCycles: \033[0m{blockCycles}")
    print(f"\033[96mnameMax: \033[0m{nameMax}")
    print(f"\033[96mfileMax: \033[0m{fileMax}")
    print(f"\033[96mattrMax: \033[0m{attrMax}")
    print(f"\033[96mbaseAddr: \033[0m{baseAddr}")
    print(f"--------------------------------")
    print(f"\033[96mos_helper_path: \033[0m{os_helper_path}")
    print(f"\033[96mmutexCreate: \033[0m{mutexCreate}")
    print(f"\033[96mmutexDelete: \033[0m{mutexDelete}")
    print(f"\033[96mmutexLock: \033[0m{mutexLock}")
    print(f"\033[96mmutexUnlock: \033[0m{mutexUnlock}")
    print(f"--------------------------------")
    print(f"\033[96mdrv_src_path: \033[0m{drv_src_path}")
    print(f"\033[96minit_func: \033[0m{init_func}")
    print(f"\033[96mread_func: \033[0m{read_func}")
    print(f"\033[96mwrite_func: \033[0m{write_func}")
    print(f"\033[96merase_func: \033[0m{erase_func}")
    print(f"\033[96msync_func: \033[0m{sync_func}")    
    print(f"--------------------------------")
    lines.append("/****************************** HW DRIVER INCLUDE *******************************/")
    lines.append(f"#define CHIP_NAME \"{chipName}\"")
    lines.append("")
    lines.append(f"#include \"{drv_src_path}\"")
    lines.append("")
    lines.append("/****************************** MACRO DEFINITIONS *******************************/")
    lines.append(f"#define FS_NAME \"{fs.get('name', '')}\"")
    lines.append(f"#define LITTLEFS_CAPACITY_BYTES     ({capacityBytes})")
    lines.append("")
    lines.append(f"#define LITTLEFS_GEOMETRY_READ_SIZE       ({readSize}) //bytes")
    lines.append(f"#define LITTLEFS_GEOMETRY_PROG_SIZE       ({progSize}) //bytes")
    lines.append(f"#define LITTLEFS_GEOMETRY_BLOCK_SIZE      ({blockSize}) //bytes")
    lines.append(f"#define LITTLEFS_GEOMETRY_BLOCK_COUNT     ({blockCount}) //blocks")
    lines.append(f"#define LITTLEFS_GEOMETRY_CACHE_SIZE      ({cacheSize}) //bytes")
    lines.append(f"#define LITTLEFS_GEOMETRY_LOOKAHEAD_SIZE  ({lookaheadSize}) //bytes")
    lines.append(f"#define LITTLEFS_GEOMETRY_BLOCK_CYCLES    ({blockCycles})")
    lines.append(f"#define LITTLEFS_GEOMETRY_NAME_MAX        ({nameMax}) //bytes")
    lines.append(f"#define LITTLEFS_GEOMETRY_FILE_MAX        ({fileMax}) //files")
    lines.append(f"#define LITTLEFS_GEOMETRY_ATTR_MAX        ({attrMax})")
    lines.append(f"#define LITTLEFS_GEOMETRY_BASE_ADDR       ({baseAddr})")
    lines.append("")    
    lines.append(f"#define LITTLEFS_MUTEX_CREATE  {mutexCreate}")
    lines.append(f"#define LITTLEFS_MUTEX_DELETE  {mutexDelete}")
    lines.append(f"#define LITTLEFS_MUTEX_LOCK    {mutexLock}")
    lines.append(f"#define LITTLEFS_MUTEX_UNLOCK  {mutexUnlock}")
    lines.append("")
    lines.append(f"#define STORAGE_DRV_FUNC_INIT  {init_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_READ  {read_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_PROG  {write_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_ERASE {erase_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_SYNC  {sync_func}")
    lines.append("")

    lines.append(f"#include \"{os_helper_path}\"")
    lines.append("")
    lines.append(
    """#define FS_HARDWARE_INIT(error_out) \\                   
                do { \\
                    error_out = ERROR_FAILURE;
                    //initialize the storage driver                    
                    if(0 == STORAGE_DRV_FUNC_INIT()) \\
                    { \\
                         //just create the mutex for littlefs, fsInit() function  \\
                        if(TRUE == LITTLEFS_MUTEX_CREATE();) \\
                        { \\
                            error_out = NO_ERROR; \\
                        } \\
                    } \\                    
                } while (0)"""
    )

def _append_flashfs_defines(lines: list, fs: dict) -> None:
    """Append FlashFS-specific defines from fs config."""

    flash = fs.get("flash", {})

    flash = flash.get("geometry", {})
    base_addr = flash.get("baseAddr", "0x00000000")
    if isinstance(base_addr, int):
        base_addr = f"0x{base_addr:08X}"
    total_size = int(flash.get("totalSize", 0))
    erase_block_size = int(flash.get("eraseBlockSize", 0))
    prog_min_size = int(flash.get("progMinSize", 0))

    hw_func = fs.get("flashHwFunc", {})
    drv_src_path = hw_func.get("drvSrcPath", "")
    read_func = hw_func.get("readFunc", "NOT_FOUND_FUNC");
    write_func = hw_func.get("writeFunc", "NOT_FOUND_FUNC");
    erase_func = hw_func.get("eraseFunc", "NOT_FOUND_FUNC");
    sync_func = hw_func.get("syncFunc", "NOT_FOUND_FUNC");   

    print(f"--------------------------------")
    print(f"\033[96mbase_addr: \033[0m{base_addr}")
    print(f"\033[96mtotal_size: \033[0m{total_size}")
    print(f"\033[96merase_block_size: \033[0m{erase_block_size}")
    print(f"\033[96mprog_min_size: \033[0m{prog_min_size}")
    print(f"--------------------------------")
    print(f"\033[96mdrv_src_path: \033[0m{drv_src_path}")
    print(f"\033[96mread_func: \033[0m{read_func}")
    print(f"\033[96mwrite_func: \033[0m{write_func}")
    print(f"\033[96merase_func: \033[0m{erase_func}")
    print(f"\033[96msync_func: \033[0m{sync_func}")
    print(f"--------------------------------")

    lines.append("/****************************** HW DRIVER INCLUDE *******************************/")
    lines.append(f"#include \"{drv_src_path}\"")
    lines.append("")
    lines.append("/****************************** MACRO DEFINITIONS *******************************/")
    lines.append(f"#define FLASHFS_BASE_ADDR        ({base_addr})")
    lines.append(f"#define FLASHFS_TOTAL_SIZE       ({total_size})")
    lines.append(f"#define FLASHFS_ERASE_BLOCK_SIZE ({erase_block_size})")
    lines.append(f"#define FLASHFS_PROG_MIN_SIZE    ({prog_min_size})")
    lines.append("")
    lines.append(f"#define STORAGE_DRV_FUNC_READ    {read_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_PROG    {write_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_ERASE   {erase_func}")
    lines.append(f"#define STORAGE_DRV_FUNC_SYNC    {sync_func}")
    lines.append("")

    lines.append(
        """#define FS_HARDWARE_INIT(error_out) \\                   
                    do { \\                        
                        FlashFsOps ops = { \\
                            .read = STORAGE_DRV_FUNC_READ, \\
                            .prog = STORAGE_DRV_FUNC_PROG, \\
                            .erase = STORAGE_DRV_FUNC_ERASE, \\
                            .sync = STORAGE_DRV_FUNC_SYNC \\
                        }; \\
                        
                        FlashFsGeom cfg = { \\
                            .baseAddr = FLASHFS_BASE_ADDR, \\
                            .totalSize = FLASHFS_TOTAL_SIZE, \\
                            .eraseBlockSize = FLASHFS_ERASE_BLOCK_SIZE, \\
                            .progMinSize = FLASHFS_PROG_MIN_SIZE \\
                        }; \\
                        
                        error_out = flashFsConfigure(&ops, &cfg); \\
                        if(NO_ERROR == error_out) \\
                        { \\
                            error_out = flashFsFormat(); \\ 
                        }\\
                    } while (0)"""
    )

def _append_pc_simulator_defines(lines: list, fs: dict) -> None:
    """Append PC Simulator-specific defines from fs config."""

    root_path = fs.get("rootPath", "")
    
    print(f"--------------------------------")
    print(f"\033[96mroot_path: \033[0m{root_path}")
    print(f"--------------------------------")

    lines.append("/****************************** MACRO DEFINITIONS *******************************/")
    lines.append(f"#define PC_SIMULATOR_ROOT_PATH \"{root_path}\"")
    lines.append("")
    lines.append(
    """#define FS_HARDWARE_INIT(error_out) \\                   
                do { \\                        
                    error_out = NO_ERROR; \\                                          
                } while (0)"""
    )

def generate_config_h(cus_fs: Path) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    lines = [
        "/******************************************************************************",
        "* designed by   : Zafer Satilmis",
        "* hype-man      : Judas Priest - Night Crawler",
        f"* customer      : {cus_fs.parent.parent.name}",
        "* generated by  : generate_fs_port_config.py",
        f"* generated on  : {now}",
        "******************************************************************************/",
        "/******************************************************************************",
        "* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"* Customer Name: {cus_fs.parent.parent.name}",
        "* Generated from customer fs_config.json.",
        "******************************************************************************/",
        "#ifndef __FS_PORT_CONFIG_H__",
        "#define __FS_PORT_CONFIG_H__",
        "",

        f'#include "{cus_fs.parent.parent.name}/Fs/cus_fs_port_config.h"',
    ]

    lines.append("")
    lines.append("#endif /* __FS_PORT_CONFIG_H__ */")
    lines.append("")

    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(
        description="Generate fs_port_config.h from customer's fs_config.json.",
        epilog="""
Examples:
  %(prog)s --customer ZD_0101
    Reads  Customers/ZD_0101/Fs/fs_config.json
    Writes Customers/ZD_0101/Fs/fs_port_config.h

  %(prog)s -h
    Show this help message.
""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--customer",
        required=True,
        metavar="NAME",
        help="Customer name (e.g. ZD_0101). Resolves to Customers/<customer>/Fs/fs_config.json",
    )
    parser.add_argument(
        "--script-dir",
        default=None,
        metavar="DIR",
        help="Directory containing this script (default: auto-detect from script location)",
    )
    args = parser.parse_args()

    script_path = os.path.realpath(__file__)
    script_dir = os.path.dirname(script_path)
    if args.script_dir:
        script_dir = os.path.realpath(args.script_dir)

    customers_root = script_dir
    json_path = os.path.join(customers_root, args.customer, "Fs", "fs_config.json")
    out_path = os.path.join(customers_root, args.customer, "Fs", "cus_fs_port_config.h")

    if not os.path.isfile(json_path):
        print(f"Error: Config file not found: {json_path}", file=sys.stderr)
        sys.exit(1)

    with open(json_path, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    script_name = os.path.basename(__file__)
    text = generate_cus_fs_port_config_h(cfg, args.customer, script_name)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)

    fs_port_h = os.path.join(script_dir, "FS_Port_Config.h")

    with open(fs_port_h, "w", encoding="utf-8") as f:
        f.write(generate_config_h(Path(out_path)))
    
    print(f"\033[94mGenerated cus_fs_port_conf: \033[0m{out_path}")
    print(f"\033[94mGenerated FS_Port_Conf: \033[0m{fs_port_h}")


if __name__ == "__main__":
    main()
