/******************************************************************************
* designed by   : Zafer Satilmis
* hype-man      : Sexen - Permitted Boots
* customer      : Stm407Eva
* generated by  : generate_logger_service.py
* generated on  : 2026-04-20 12:25:17
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: Stm407Eva
* Generated from customer logger_config.json via generate_logger_service.py.
******************************************************************************/
#ifndef __LOGGER_SERVICE_CONFIG_H__
#define __LOGGER_SERVICE_CONFIG_H__
    /*********************************INCLUDES*************************************/

/* generated by: generate_logger_service.py */
/* customer name: Stm407Eva */

#include "Stm407Eva/Logger/Cus_LoggerService_Conf.h"

#endif /* __LOGGER_SERVICE_CONFIG_H__ */

/********************************* End Of File ********************************/
