/******************************************************************************
* designed by   : Zafer Satilmis
* hype-man      : EPICA - Cry for the Moon
* customer      : LinuxGcc
* generated by  : generate_network_service.py
* generated on  : 2026-04-20 08:11:29
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: LinuxGcc
* Generated from customer network_config.json via generate_network_service.py.
******************************************************************************/
#ifndef __CUS_NETWORK_CONFIG_H__
#define __CUS_NETWORK_CONFIG_H__


#define NET_INTERFACE_COUNT     (1)
#define NET_STACK_NAME          "Linux"
#define NET_STACK_VERSION       "0"
#define NET_STACK_CONFIG_FILE   ""
#define NET_STACK_STACK_PATH    ""

#include "Services/Network/Interfaces/Linux/AppLinuxTcpIpStack.h"
#define NET_STACK_STACK_INIT_FUNCTION       (appLinuxTcpIpStackInit)

#define NET_STACK_DHCP_CLIENT   false
#define NET_STACK_DHCP_SERVER   false
#define NET_STACK_DNS_USE       false
#define NET_STACK_DNS_SERVER_LIST "8.8.8.8,8.8.4.4"

/****** Ethernet Interface Configuration **************************************/
#include "Services/Network/Interfaces/Linux/AppLinuxEthMng.h"
#define ETH_APP_MANAGER_START_FUNCTION            (appLinuxEthMngStart)
#define ETH_APP_MANAGER_CLOSE_FUNCTION            (appLinuxEthMngClose)
#define ETH_APP_MANAGER_RECONNECT_FUNCTION        (appLinuxEthMngReconnect)
#define ETH_APP_MANAGER_IS_NETWORK_READY_FUNCTION (appLinuxEthMngIsNetworkReady)

#define ETH_INTERFACE_NUMBER        (0)
#define ETH_IF_NAME                 "eth0"

/****** PUBLIC FUNCTIONS **************************************/
/**
 * @brief   Initialize the TCP/IP stack
 * @return  if everything is OK, return SUCCESS
 *          otherwise return FAILURE
 */
RETURN_STATUS networkServiceInitTCPIPStack(void);
/**
 * @brief   Start the network interfaces
 * @return  if everything is OK, return SUCCESS
 *          otherwise return FAILURE
 */
RETURN_STATUS networkServiceStartInterfaces(void);


#endif /* __CUS_NETWORK_CONFIG_H__ */

/******************************** End Of File *********************************/