/******************************************************************************
* designed by   : Zafer Satilmis
* hype-man      : EPICA - Cry for the Moon 
* customer      : LinuxGcc
* generated by  : generate_network_config.py
* generated on  : 2026-04-12 14:21:51
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: LinuxGcc
* Generated from customer network_config.json via generate_network_config.py.
******************************************************************************/
#ifndef __CUS_NETWORK_CONFIG_H__
#define __CUS_NETWORK_CONFIG_H__

 
#define NET_INTERFACE_COUNT     (2)

/****** Ethernet Interface Configuration **************************************/
#define ETH_APP_MANAGER_PATH    "Services/Network/Interfaces/CycloneTcp/AppCycloneEthMng.h"
#define ETH_INTERFACE_NUMBER    (0)
#define ETH_IF_NAME             "eth0"
#define ETH_HOST_NAME           "aviora"
#define ETH_MAC_ADDR            "02:03:04:05:06:07"

#define ETH_IP_ADDR             "192.168.1.35"
#define ETH_SUBNET_MASK         "255.255.255.0"
#define ETH_DEFAULT_GATEWAY     "192.168.1.254"

#define ETH_DRIVER_SPI_DRIVER           spiDriver
#define ETH_DRIVER_SPI_LINE             ETH_SPI_LINE_0
#define ETH_DRIVER_SPI_DRIVER_PATH      "Drivers/ENC28J60/enc28j60_spi_driver.h"
#define ETH_DRIVER_EXT_INT_DRIVER       extIntDriver
#define ETH_DRIVER_EXT_INT_LINE         ETH_EXTINT_LINE_0
#define ETH_DRIVER_EXT_INT_DRIVER_PATH  "Drivers/ENC28J60/enc28j60/enc28j60_extint_driver.h"

/****** PPP Interface Configuration ******************************************/
#define PPP_APP_MANAGER_PATH      "Services/Network/Interfaces/CycloneTcp/AppCyclonePPPMng.h"
#define PPP_INTERFACE_NUMBER     (1)
#define PPP_IF_NAME              "ppp0"

#define PPP_APP_PIN_CODE          NULL
#define PPP_APP_APN               "zd.iot"
#define PPP_APP_PHONE_NUMBER      "*99#"
#define PPP_APP_TIMEOUT           10000
#define PPP_APP_UART_LINE         LINE_0
#define PPP_APP_UART_DRIVER_PATH  "Units/System/src/uart_driver.h"

#endif /* __CUS_NETWORK_CONFIG_H__ */

/******************************** End Of File *********************************/