/******************************************************************************
* designed by  : Zafer Satilmis
* hype-man     : Judas Priest - Night Crawler
* customer     : Stm407Eva
* version      : 1.1
* releaseDate  : 2026-04-13
* generated by : generate_fs_port_config.py
* generated on : 2026-04-16 00:36:39
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: Stm407Eva
* Generated from customer fs_config.json. Only used units are included.
******************************************************************************/

#ifndef __CUS_FS_PORT_CONFIG_H__
#define __CUS_FS_PORT_CONFIG_H__

#ifndef ERROR_NOT_READY
   #define ERROR_NOT_READY  9999
#endif
#ifndef ERROR_ALREADY_EXISTS
   #define ERROR_ALREADY_EXISTS  9998
#endif

#define USE_FLASHFS 1
#define FS_NAME "FlshFs"
/****************************** INCLUDE FS *******************************/
//FatFs port?
#if defined(USE_FATFS)
   #include "fs_port_fatfs.h"
//littleFS port?
#elif defined(USE_LITTLEFS)
   #include "fs_port_littlefs.h"
//FlashFS port?
#elif defined(USE_FLASHFS)
   #include "fs_port_flashFS.h"
//FlashLink port?
#elif defined(USE_FLASHLINK)
   #include "fs_port_flashLink.h"
//PC Simulator / Windows / POSIX (JSON: pc_simulator veya _WIN32/__linux__)
#elif defined(USE_PC_SIMULATOR)
   #include "fs_port_posix.h"
//Custom port?
#elif defined(USE_CUSTOM_FS)
   #include "fs_port_custom.h"
//FS not found in fsLib (activeFsName not in fsLib)
#elif defined(USE_NOT_FOUND_FS)
   #error "USE_NOT_FOUND_FS fs is not found"
//FS not used (useStore=false)
#elif defined(USE_NOT_USED_FS)
   #error "USE_NOT_USED_FS fs is not used"
#endif

/****************************** HW DRIVER INCLUDE *******************************/
#include "McuCoreDrivers/inc/McuInternalFlashDrv_Stm32f407.h"

/****************************** MACRO DEFINITIONS *******************************/
#define FLASHFS_BASE_ADDR        (0x08040000)
#define FLASHFS_TOTAL_SIZE       (131072)
#define FLASHFS_ERASE_BLOCK_SIZE (131072)
#define FLASHFS_PROG_MIN_SIZE    (4)

#define STORAGE_DRV_FUNC_READ    internalStm32f407FlashRead
#define STORAGE_DRV_FUNC_PROG    internalStm32f407FlashProg
#define STORAGE_DRV_FUNC_ERASE   internalStm32f407FlashErase
#define STORAGE_DRV_FUNC_SYNC    internalStm32f407FlashSync

#define FS_HARDWARE_INIT(error_out) \                   
                    do { \                        
                        FlashFsOps ops = { \
                            .read = STORAGE_DRV_FUNC_READ, \
                            .prog = STORAGE_DRV_FUNC_PROG, \
                            .erase = STORAGE_DRV_FUNC_ERASE, \
                            .sync = STORAGE_DRV_FUNC_SYNC \
                        }; \
                        FlashFsGeom cfg = { \
                            .baseAddr = FLASHFS_BASE_ADDR, \
                            .totalSize = FLASHFS_TOTAL_SIZE, \
                            .eraseBlockSize = FLASHFS_ERASE_BLOCK_SIZE, \
                            .progMinSize = FLASHFS_PROG_MIN_SIZE \
                        }; \
                        error_out = flashFsConfigure(&ops, &cfg); \
                        if(NO_ERROR == error_out) \
                        { \
                            error_out = flashFsFormat(); \ 
                        }\
                    } while (0)
#endif /* __CUS_FS_PORT_CONFIG_H__ */
