/******************************************************************************
* designed by   : Zafer Satilmis
* hype-man      : Sexen - Stolen Chastity
* customer      : LinuxGcc
* generated by  : generate_logger_service.py
* generated on  : 2026-04-08 13:29:44
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: LinuxGcc
* Generated from customer logger_config.json via generate_logger_service.py.
******************************************************************************/
#ifndef __CUS_LOGGER_SERVICE_CONFIG_H__
#define __CUS_LOGGER_SERVICE_CONFIG_H__
/*********************************INCLUDES*************************************/
#include "Project_Conf.h"

/************************* GLOBAL VARIBALE REFERENCES *************************/
/* sysLogger */
extern S32 g_sysLoggerID;
/****************************** MACRO DEFINITIONS *******************************/
#define USE_LOGGER_SERVICE (ENABLE)

#define LOGGER_QUEUE_SIZE     (10)
#define LOGGER_LOG_MAX_LENGTH (128)

/****** Loggers List *****/
#define ACTIVE_LOGGER_COUNT (1)

#define APP_LOG_REC(logID, str) appLogRec(logID, str);
/** logger-1 sysLogger configuration **/
#define LOGGER_SYS_NAME               "sysLogger"
#define LOGGER_SYS_USE                (TRUE)
#define LOGGER_SYS_FS_PATH            "Middleware/MiddComm/Midd_FS/fs_port.h"
#define LOGGER_SYS_OPEN_FUNC          (fsOpenFile)
#define LOGGER_SYS_READ_FUNC          (fsReadFile)
#define LOGGER_SYS_WRITE_FUNC         (fsWriteFile)
#define LOGGER_SYS_CLOSE_FUNC         (fsCloseFile)
#define LOGGER_SYS_LOG_PATH           "log"
#define LOGGER_SYS_FILE_SIZE          (10240)
#define LOGGER_SYS_TOTAL_LOG_SIZE     (102400)
#define LOGGER_SYS_TIME_INFO_USE      (TRUE)
#define LOGGER_SYS_TIME_INFO_FORMAT   (FIRST_YEAR)

/************************* GLOBAL FUNCTION DEFINITIONS ************************/
RETURN_STATUS appLogStartLoggers(void);

#endif /* __CUS_LOGGER_SERVICE_CONFIG_H__ */

/********************************* End Of File ********************************/
