/******************************************************************************
* designed by  : Zafer Satilmis
* hype-man     : Judas Priest - Night Crawler
* customer     : LinuxGcc
* version      : 1.1
* releaseDate  : 2026-04-06
* generated by : generate_fs_port_config.py
* generated on : 2026-04-20 08:11:29
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: LinuxGcc
* Generated from customer fs_config.json. Only used units are included.
******************************************************************************/

#ifndef __CUS_FS_PORT_CONFIG_H__
#define __CUS_FS_PORT_CONFIG_H__

#ifndef ERROR_NOT_READY
   #define ERROR_NOT_READY  9999
#endif
#ifndef ERROR_ALREADY_EXISTS
   #define ERROR_ALREADY_EXISTS  9998
#endif

#define USE_PC_SIMULATOR 1

/****************************** INCLUDE FS *******************************/
//FatFs port?
#if defined(USE_FATFS)
   #include "fs_port_fatfs.h"
//littleFS port?
#elif defined(USE_LITTLEFS)
   #include "fs_port_littlefs.h"
//FlashFS port?
#elif defined(USE_FLASHFS)
   #include "fs_port_flashFS.h"
//FlashLink port?
#elif defined(USE_FLASHLINK)
   #include "fs_port_flashLink.h"
//PC Simulator / Windows / POSIX (JSON: pc_simulator veya _WIN32/__linux__)
#elif defined(USE_PC_SIMULATOR)
   #include "fs_port_posix.h"
//Custom port?
#elif defined(USE_CUSTOM_FS)
   #include "fs_port_custom.h"
//FS not found in fsLib (activeFsName not in fsLib)
#elif defined(USE_NOT_FOUND_FS)
   #error "USE_NOT_FOUND_FS fs is not found"
//FS not used (useStore=false)
#elif defined(USE_NOT_USED_FS)
   #error "USE_NOT_USED_FS fs is not used"
#endif

/****************************** MACRO DEFINITIONS *******************************/
#define FS_NAME  "pc_simulator"
#define PC_SIMULATOR_ROOT_PATH "DevFs/"

#define FS_HARDWARE_INIT(error_out)\
                do {\
                    error_out = NO_ERROR;\
                } while (0)
#endif /* __CUS_FS_PORT_CONFIG_H__ */
