/******************************************************************************
* designed by  : Zafer Satilmis
* hype-man     : Pentagram/Mezarkabul - Secret Missile
* customer     : Stm407Eva
* version      : 1.1
* releaseDate  : 2026-04-13
* generated by : generate_protocol_config.py
* generated on : 2026-04-13 20:51:16
*******************************************************************************/

/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: Stm407Eva
* Generated from customer protocol_config.json. Only used units are included.
******************************************************************************/
/****************************** IFNDEF & DEFINE ******************************/
#ifndef __CUS_PROTOCOL_CONFIG_H__
#define __CUS_PROTOCOL_CONFIG_H__
/********************************* INCLUDES **********************************/
#include "Project_Conf.h"
/***************************** MACRO DEFINITIONS *****************************/

#define ACTIVE_PROTOCOL_NUMBER (1)

/****** PROTOCOL - ORION_TLV *****************************/
#include "AppZMeterGw/Services/Protocol/inc/AppProtocolOrionTLV.h"
#define APP_ORION_TLV_PROTOCOL_INIT_FUNC(serialNumber)   appProtocolOrionTLVInit(serialNumber)
#define APP_ORION_TLV_PROTOCOL_START_FUNC()              appProtocolOrionTLVStart()
#define APP_ORION_TLV_PROTOCOL_STOP_FUNC()               appProtocolOrionTLVStop()
#define APP_ORION_TLV_PROTOCOL_PUT_INCOMING_FUNC(channel, data, dataLength) appProtocolOrionTLVPutIncomingMessage(channel, data, dataLength)

#define ORION_TLV_DEFAULT_SERVER_IP       "192.168.1.102"
#define ORION_TLV_DEFAULT_PUSH_PORT       (8723)
#define ORION_TLV_DEFAULT_DEVICE_IP       "192.168.1.35"
#define ORION_TLV_DEFAULT_PULL_PORT       (2622)

/******* PROTOCOL - INIT *****************************/
#define INIT_PROTOCOLS(setErrorFlag, serialNum)   \
                                    do{ \
                                        setErrorFlag = 0;\
                                        if(!setErrorFlag) {setErrorFlag |= APP_ORION_TLV_PROTOCOL_INIT_FUNC(serialNum); zosDelayTask(1000); } \
                                        if(!setErrorFlag) {setErrorFlag |= APP_ORION_TLV_PROTOCOL_START_FUNC(); zosDelayTask(1000); } \
                                    } while(0)


/********************************* SENSOR DEFINITIONS *************************/
#define ACTIVE_SENSOR_NUMBER (1)

#include "AppZMeterGw/Services/Protocol/Test_Server/MeterTcpComm.h"
#include "AppZMeterGw/Services/Protocol/inc/AppMeterOperations.h"
#define SENSOR_ELECTRICITYMETER_INITIALIZE_FUNC(setErrorFlag)   \
                                    do{ \
                                        /* Sensor initialization code here */ \
                                        MeterCommInterface_t meterComm = { \
                                            .meterCommInit        = meterTcpCommInit, \
                                            .meterCommSend        = meterTcpCommSend, \
                                            .meterCommReceive     = meterTcpCommReceive, \
                                            .meterCommSetBaudrate = meterTcpCommSetBaudrate, \
                                        }; \
                                        setErrorFlag |= appMeterOperationsStart(&meterComm); \
                                    } while(0)

#define INIT_SENSORS(setErrorFlag)   \
                                    do{ \
                                        setErrorFlag = 0;\
                                        if(!setErrorFlag) SENSOR_ELECTRICITYMETER_INITIALIZE_FUNC(setErrorFlag); \
                                    } while(0)


/******************************* TYPE DEFINITIONS *****************************/

/************************* GLOBAL VARIBALE REFERENCES *************************/

/************************* GLOBAL FUNCTION DEFINITIONS ************************/

#endif /* __CUS_PROTOCOL_CONFIG_H__ */

/********************************* End Of File ********************************/
