/******************************************************************************
* designed by  : Zafer Satilmis
* hype-man     : Pentagram/Mezarkabul - Secret Missile
* customer     : ZD_0101
* version      : 1.1
* releaseDate  : 2026-03-19
* generated by : generate_protocol_config.py
* generated on : 2026-04-03 20:04:29
*******************************************************************************/

/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: ZD_0101
* Generated from customer protocol_config.json. Only used units are included.
******************************************************************************/
/****************************** IFNDEF & DEFINE ******************************/
#ifndef __CUS_PROTOCOL_CONFIG_H__
#define __CUS_PROTOCOL_CONFIG_H__
/********************************* INCLUDES **********************************/
#include "Project_Conf.h"
/***************************** MACRO DEFINITIONS *****************************/

#define ACTIVE_PROTOCOL_NUMBER (1)

/****** PROTOCOL - RIGEL_MQ *****************************/
#include "Application/AppZMeterGw/Services/Protocol/inc/AppProtocolRigelMq.h"
#define APP_RIGEL_MQ_PROTOCOL_INIT_FUNC(serialNumber)   appProtocolRigelMqInit(serialNumber)
#define APP_RIGEL_MQ_PROTOCOL_START_FUNC()              appProtocolRigelMqStart()
#define APP_RIGEL_MQ_PROTOCOL_STOP_FUNC()               appProtocolRigelMqStop()
#define APP_RIGEL_MQ_PROTOCOL_PUT_INCOMING_FUNC(channel, data, dataLength) appProtocolRigelMqPutIncomingMessage(channel, data, dataLength)

#define RG_RIGEL_DEFAULT_MQTT_BROKER_IP       "127.0.0.1"
#define RG_RIGEL_DEFAULT_MQTT_BROKER_PORT     (1883)
#define RG_RIGEL_DEFAULT_MQTT_USER_NAME       "ZDUser"
#define RG_RIGEL_DEFAULT_MQTT_PASSWORD        "ZDUserPass"

#define RG_RIGEL_DEFAULT_DEVICE_IP            "127.0.0.1"
#define RG_RIGEL_DEFAULT_PULL_PORT            (2622)

#define RG_RIGEL_DEFAULT_MQTT_REQUEST_TOPIC   "avi/request"
#define RG_RIGEL_DEFAULT_MQTT_RESPONSE_TOPIC  "avi/response"

/******* PROTOCOL - INIT *****************************/
#define INIT_PROTOCOLS(setErrorFlag)   \
                                    do{ \
                                        setErrorFlag = 0;\
                                        if(!setErrorFlag) {setErrorFlag |= APP_RIGEL_MQ_PROTOCOL_INIT_FUNC(setErrorFlag); zosDelay(1000); } \
                                        if(!setErrorFlag) {setErrorFlag |= APP_RIGEL_MQ_PROTOCOL_START_FUNC(); zosDelay(1000); } \
                                    } while(0)


/********************************* SENSOR DEFINITIONS *************************/
#define ACTIVE_SENDOR_NUMBER (1)

#include "Application/AppZMeterGw/Services/Protocol/Test_Server/MeterTcpComm.h"
#define SENSOR_ELECTRICITYMETER_INITIALIZE_FUNC(setErrorFlag)   \
                                    do{ \
                                        /* Sensor initialization code here */ \
                                        MeterCommInterface_t meterComm = { \
                                            .meterCommInit        = meterTcpCommInit, \
                                            .meterCommSend        = meterTcpCommSend, \
                                            .meterCommReceive     = meterTcpCommReceive, \
                                            .meterCommSetBaudrate = meterTcpCommSetBaudrate, \
                                        }; \
                                        setErrorFlag |= appMeterOperationsStart(&meterComm); \

                                    } while(0)

#define INIT_SENSORS(setErrorFlag)   \
                                    do{ \
                                        setErrorFlag = 0;\
                                        if(!setErrorFlag) SENSOR_ELECTRICITYMETER_INITIALIZE_FUNC(setErrorFlag); \
                                    } while(0)


/******************************* TYPE DEFINITIONS *****************************/

/************************* GLOBAL VARIBALE REFERENCES *************************/

/************************* GLOBAL FUNCTION DEFINITIONS ************************/

#endif /* __CUS_PROTOCOL_CONFIG_H__ */

/********************************* End Of File ********************************/
