/*
 * AppNetworkService_InterfaceLoader.c
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: Python Configuration Parser Script
 * Source: Device configuration JSON file
 *
 * This file selectively includes interface implementations based on the
 * configuration generated from the JSON device configuration.
 * Only enabled interfaces are included; disabled interfaces are omitted.
 *
 * Structure:
 * 1. Include configuration (defines interface enable/disable flags)
 * 2. Conditionally include interface implementation files
 * 3. Define interface state monitoring and reconnection functions
 *    (only enabled interfaces are monitored)
 *
 * This file is #include'd by AppNetworkService.c at the END
 * DO NOT compile this file separately.
 */

/*==============================================================================
 * Configuration and Interface Selection
 *============================================================================*/

/* Load configuration structure and initialization coordinator */
#include "AppNetworkService_Config.c"

/*==============================================================================
 * Conditional Interface File Inclusion
 * Based on enabled flag in gAppNetworkServiceConfig
 *============================================================================*/

/* GSM Interface Implementation */
#if defined(GSM_INTERFACE_ENABLED) || 1  /* Replace with: if enabled in config */
#include "AppNetworkService_GSM.c"
#endif

/* Ethernet Interface Implementation */
#if defined(ETH_INTERFACE_ENABLED) || 1  /* Replace with: if enabled in config */
#include "AppNetworkService_ETH.c"
#endif

/*==============================================================================
 * Interface State Monitoring Functions
 * Only included/executed for enabled interfaces
 *============================================================================*/

/**
 * priv_UpdateGsmState - Monitor GSM Interface State
 * Called periodically by AppNetworkService_Task()
 * Only executed if GSM interface is enabled in configuration
 */
static void priv_UpdateGsmState(void)
{
    bool wasConnected = gNetworkService_state.gsmState.connected;
    bool isNetworkReady = false;

    /* Check if GSM interface is enabled and initialized */
    if (!gAppNetworkServiceConfig.gsmConfig.enabled || !gNetworkService_state.gsmState.initialized) {
        return;
    }

    /* Query AppGsmManager for current network status */
    isNetworkReady = (bool)appGsmMngIsNetworkReady();

    /* Detect connection state changes */
    if (wasConnected && !isNetworkReady) {
        /* Connection was lost */
        gNetworkService_state.gsmState.connected = false;
        priv_PublishNetworkEvent(0x02, 0, 0); /* GSM_DISCONNECTED */
    }
    else if (!wasConnected && isNetworkReady) {
        /* Connection was established */
        gNetworkService_state.gsmState.connected = true;
        priv_PublishNetworkEvent(0x01, 0, 0); /* GSM_CONNECTED */
    }
}

/**
 * priv_UpdateEthState - Monitor Ethernet Interface State
 * Called periodically by AppNetworkService_Task()
 * Only executed if Ethernet interface is enabled in configuration
 */
static void priv_UpdateEthState(void)
{
    /* Check if Ethernet interface is enabled and initialized */
    if (!gAppNetworkServiceConfig.ethConfig.enabled) {
        return;
    }

    /* TODO: Query Ethernet driver for current status
     * - Check if link is up
     * - Detect connection loss
     * - Monitor link status changes
     * - Update gNetworkService_state.ethState.connected
     * - Publish events if state changes
     */
}

/*==============================================================================
 * Interface Reconnection Handling
 *============================================================================*/

/**
 * priv_HandleReconnection - Handle Reconnection Logic
 * Called periodically by AppNetworkService_Task()
 * Applies to all enabled interfaces
 */
static void priv_HandleReconnection(void)
{
    /* TODO: Implement reconnection strategy
     * - Detect disconnection when interface was previously connected
     * - Implement exponential backoff for reconnection attempts
     * - Respect configured reconnection parameters (retry count, interval)
     * - Apply to both GSM and Ethernet interfaces as enabled
     */
}

/*** End Of File ***/
