/******************************************************************************
* designed by  : Zafer Satilmis
* hype-man     : Judas Priest - Night Crawler
* customer     : ZD_0101
* version      : 1.1
* releaseDate  : 2026-03-20
* generated by : generate_fs_port_config.py
* generated on : 2026-04-08 13:38:38
******************************************************************************/
/******************************************************************************
* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
* Customer Name: ZD_0101
* Generated from customer fs_config.json. Only used units are included.
******************************************************************************/

#ifndef __CUS_FS_PORT_CONFIG_H__
#define __CUS_FS_PORT_CONFIG_H__

#ifndef ERROR_NOT_READY
   #define ERROR_NOT_READY  9999
#endif
#ifndef ERROR_ALREADY_EXISTS
   #define ERROR_ALREADY_EXISTS  9998
#endif

#define USE_FLASHLINK 1

/****************************** INCLUDE FS *******************************/
//FatFs port?
#if defined(USE_FATFS)
   #include "fs_port_fatfs.h"
//littleFS port?
#elif defined(USE_LITTLEFS)
   #include "fs_port_littlefs.h"
//FlashFS port?
#elif defined(USE_FLASHFS)
   #include "fs_port_flashFS.h"
//FlashLink port?
#elif defined(USE_FLASHLINK)
   #include "fs_port_flashLink.h"
//PC Simulator / Windows / POSIX (JSON: pc_simulator veya _WIN32/__linux__)
#elif defined(USE_PC_SIMULATOR)
   #include "fs_port_posix.h"
//Custom port?
#elif defined(USE_CUSTOM_FS)
   #include "fs_port_custom.h"
//FS not found in fsLib (activeFsName not in fsLib)
#elif defined(USE_NOT_FOUND_FS)
   #error "USE_NOT_FOUND_FS fs is not found"
//FS not used (useStore=false)
#elif defined(USE_NOT_USED_FS)
   #error "USE_NOT_USED_FS fs is not used"
#endif

/****************************** HW DRIVER INCLUDE *******************************/
#include "Driver/McuCoreDrivers/inc/McuInternalFlashDrv_Stm32f407.h"

/****************************** MACRO DEFINITIONS *******************************/
#define FS_NAME  "flashlink"
#define FLASHLINK_CELL_SIZE       (1024)
#define FLASHLINK_NAME_SIZE       (64)
#define FLASHLINK_CELL_DATA_SIZE  (956)
#define FLASHLINK_CELL_COUNT      (10)

#define FLASHLINK_BASE_ADDR        (0x080A0000)
#define FLASHLINK_REGION_SIZE      (131072)
#define FLASHLINK_ERASE_BLOCK_SIZE (4096)

#define STORAGE_DRV_FUNC_READ    internalStm32f407FlashRead
#define STORAGE_DRV_FUNC_PROG    internalStm32f407FlashProg
#define STORAGE_DRV_FUNC_ERASE   internalStm32f407FlashErase
#define STORAGE_DRV_FUNC_SYNC    internalStm32f407FlashSync

#define FS_HARDWARE_INIT(error_out) \                   
                    do { \                        
                        FlashLinkOps ops = { \
                            .read = STORAGE_DRV_FUNC_READ, \
                            .prog = STORAGE_DRV_FUNC_PROG, \
                            .erase = STORAGE_DRV_FUNC_ERASE, \
                            .sync = STORAGE_DRV_FUNC_SYNC \
                        }; \
                        
                        FlashLinkConfig cfg = { \
                            .baseAddr = FLASHLINK_BASE_ADDR, \
                            .regionSize = FLASHLINK_REGION_SIZE, \
                            .cellCount = FLASHLINK_CELL_COUNT, \
                            .eraseBlockSize = FLASHLINK_ERASE_BLOCK_SIZE \
                        }; \
                        
                        error_out = flashLinkInit(&ops, &cfg); \
                        if(NO_ERROR == error_out) \
                        { \
                            error_out = flashLinkFormat(); \ 
                        }\
                                               
                    } while (0)
#endif /* __CUS_FS_PORT_CONFIG_H__ */
