/******************************************************************************
* Auto-generated fs_port_config.h
* customer     : .\ZD_0101\
* version      : 1.1
* releaseDate  : 2026-03-20
* generated by : generate_fs_port_config.py
* generated on : 2026-03-22 00:05:02
******************************************************************************/

#ifndef __FS_PORT_CONFIG_H__
#define __FS_PORT_CONFIG_H__

#include "error.h"

/* Error codes used by fs_port but not in CycloneTCP error.h */
#ifndef ERROR_NOT_READY
   #define ERROR_NOT_READY  9999
#endif
#ifndef ERROR_ALREADY_EXISTS
   #define ERROR_ALREADY_EXISTS  9998
#endif

#define USE_FLASHLINK 1

//FatFs port?
#if defined(USE_FATFS)
   #include "fs_port_fatfs.h"
//littleFS port?
#elif defined(USE_LITTLEFS)
   #include "fs_port_littlefs.h"
//FlashFS port?
#elif defined(USE_FLASHFS)
   #include "fs_port_flashFS.h"
//FlashLink port?
#elif defined(USE_FLASHLINK)
   #include "fs_port_flashLink.h"
//PC Simulator / Windows / POSIX (JSON: pc_simulator veya _WIN32/__linux__)
#elif defined(USE_PC_SIMULATOR)
   #include "fs_port_posix.h"
//Custom port?
#elif defined(USE_CUSTOM_FS)
   #include "fs_port_custom.h"
//FS not found in fsLib (activeFsName not in fsLib)
#elif defined(USE_NOT_FOUND_FS)
   #error "USE_NOT_FOUND_FS fs is not found"
//FS not used (useStore=false)
#elif defined(USE_NOT_USED_FS)
   #error "USE_NOT_USED_FS fs is not used"
#endif


/******************************MACRO DEFINITIONS*******************************/
#define FLASHLINK_CELL_SIZE       (1024)
#define FLASHLINK_NAME_SIZE       (64)
#define FLASHLINK_CELL_DATA_SIZE  (956)
#define FLASHLINK_CELL_COUNT      (0)

#define FLASHLINK_BASE_ADDR        (0x080A0000)
#define FLASHLINK_REGION_SIZE      (131072)
#define FLASHLINK_ERASE_BLOCK_SIZE (4096)

#define STORAGE_DRV_FUNC_READ    internalStm32f407FlashRead
#define STORAGE_DRV_FUNC_PROG    internalStm32f407FlashProg
#define STORAGE_DRV_FUNC_ERASE   internalStm32f407FlashErase
#define STORAGE_DRV_FUNC_SYNC    internalStm32f407FlashSync

#endif /* __FS_PORT_CONFIG_H__ */
