/******************************************************************************
* Auto-generated fs_port_config.h
* customer     : New_Costomer_ZD
* version      : 1.1
* releaseDate  : 2026-01-26
* generated by : generate_fs_port_config.py
* generated on : 2026-03-18 11:05:23
******************************************************************************/

#ifndef __FS_PORT_CONFIG_H__
#define __FS_PORT_CONFIG_H__

#include "fs_port.h"  /* or core includes as needed */

#define USE_FLASHLINK 1

//FatFs port?
#if defined(USE_FATFS)
   #include "fs_port_fatfs.h"
//littleFS port?
#elif defined(USE_LITTLEFS)
   #include "fs_port_littlefs.h"
//FlashFS port?
#elif defined(USE_FLASHFS)
   #include "fs_port_flashFS.h"
//FlashLink port?
#elif defined(USE_FLASHLINK)
   #include "fs_port_flashLink.h"
//Windows port?
#elif defined(_WIN32)
   #include "fs_port_posix.h"
//POSIX port?
#elif defined(__linux__) || defined(__FreeBSD__)
   #include "fs_port_posix.h"
//Custom port?
#elif defined(USE_CUSTOM_FS)
   #include "fs_port_custom.h"
#endif

#define FLASHLINK_BASE_ADDR       0x080A0000
#define FLASHLINK_REGION_SIZE     131072
#define FLASHLINK_CELL_SIZE       1024
#define FLASHLINK_NAME_SIZE       64
#define FLASHLINK_CELL_DATA_SIZE  956

#define STORAGE_FLASH_LINK_READ_FUNC    Storage_FlashLinkRead
#define STORAGE_FLASH_LINK_PROG_FUNC    Storage_FlashLinkProg
#define STORAGE_FLASH_LINK_ERASE_FUNC   Storage_FlashLinkErase
#define STORAGE_FLASH_LINK_SYNC_FUNC    Storage_FlashLinkSync

#endif /* __FS_PORT_CONFIG_H__ */
