import argparse
import json
import os
from datetime import datetime

# Map fsLib.name -> (USE_ macro, include branch symbol)
FS_NAME_TO_MACRO = {
    "fatfs":    "USE_FATFS",
    "littlefs": "USE_LITTLEFS",
    "flashfs":  "USE_FLASHFS",
    "flashlink": "USE_FLASHLINK",
    "custom":   "USE_CUSTOM_FS",
}

SIZE_SUFFIXES = {
    "K": 1024,
    "M": 1024 * 1024,
}


def parse_size_to_bytes(size_str: str) -> int:
    """
    Parse strings like "128K", "1M", "65536" into integer bytes.
    """
    s = size_str.strip().upper()
    # Plain integer
    if s.isdigit():
        return int(s)
    # With suffix
    for suf, mul in SIZE_SUFFIXES.items():
        if s.endswith(suf):
            num = float(s[:-1])
            return int(num * mul)
    raise ValueError(f"Unsupported size format: {size_str}")


def generate_header_text(cfg: dict, script_name: str) -> str:
    """
    cfg: config JSON already loaded as dict.
    """
    customer = cfg.get("customer", "UNKNOWN_CUSTOMER")
    version = cfg.get("version", "0.0")
    release_date = cfg.get("releaseDate", "")
    store = cfg.get("store", {})
    fs_lib = store.get("fsLib", {})
    ext = store.get("extFlsh", {})

    fs_name = fs_lib.get("name", "").strip()
    cell_size = int(fs_lib.get("cellSize", 196))
    name_size = int(fs_lib.get("nameSize", 64))
    cell_data_size = int(fs_lib.get("cellDataSize", 128))

    flash_start_add = ext.get("flashStartAdd", "0x00000000")
    flash_size_str = ext.get("flashSize", "0")
    flash_size_val = parse_size_to_bytes(flash_size_str)

    read_func = ext.get("readFunc", "Storage_FlashLinkRead")
    prog_func = ext.get("progFunc", "Storage_FlashLinkProg")
    erase_func = ext.get("eraseFunc", "Storage_FlashLinkErase")
    sync_func = ext.get("syncFunc", "Storage_FlashLinkSync")

    print(f"Parsed config: customer={customer}, version={version}, fs_name={fs_name}, flash_size={flash_size_val} bytes")
    use_macro = FS_NAME_TO_MACRO.get(fs_name.lower(), "USE_CUSTOM_FS")

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []

    # Auto-generated header comment
    lines.append("/******************************************************************************")
    lines.append(f"* Auto-generated fs_port_config.h")
    lines.append(f"* customer     : {customer}")
    lines.append(f"* version      : {version}")
    lines.append(f"* releaseDate  : {release_date}")
    lines.append(f"* generated by : {script_name}")
    lines.append(f"* generated on : {now_str}")
    lines.append("******************************************************************************/")
    lines.append("")
    lines.append("#ifndef __FS_PORT_CONFIG_H__")
    lines.append("#define __FS_PORT_CONFIG_H__")
    lines.append("")
    lines.append("#include \"fs_port.h\"  /* or core includes as needed */")
    lines.append("")
    # Active FS macro
    lines.append(f"#define {use_macro} 1")
    lines.append("")

    # Include selection block, mirroring your existing pattern
    lines.append("//FatFs port?")
    lines.append("#if defined(USE_FATFS)")
    lines.append("   #include \"fs_port_fatfs.h\"")
    lines.append("//littleFS port?")
    lines.append("#elif defined(USE_LITTLEFS)")
    lines.append("   #include \"fs_port_littlefs.h\"")
    lines.append("//FlashFS port?")
    lines.append("#elif defined(USE_FLASHFS)")
    lines.append("   #include \"fs_port_flashFS.h\"")
    lines.append("//FlashLink port?")
    lines.append("#elif defined(USE_FLASHLINK)")
    lines.append("   #include \"fs_port_flashLink.h\"")
    lines.append("//Windows port?")
    lines.append("#elif defined(_WIN32)")
    lines.append("   #include \"fs_port_posix.h\"")
    lines.append("//POSIX port?")
    lines.append("#elif defined(__linux__) || defined(__FreeBSD__)")
    lines.append("   #include \"fs_port_posix.h\"")
    lines.append("//Custom port?")
    lines.append("#elif defined(USE_CUSTOM_FS)")
    lines.append("   #include \"fs_port_custom.h\"")
    lines.append("#endif")
    lines.append("")

    # FlashLink-specific macros (only meaningful when using that backend,
    # ama sen istersen her zaman üretilsin diyorsun; dolayısıyla koşulsuz yazıyorum)
    lines.append(f"#define FLASHLINK_BASE_ADDR       {flash_start_add}")
    lines.append(f"#define FLASHLINK_REGION_SIZE     {flash_size_val}")
    lines.append(f"#define FLASHLINK_CELL_SIZE       {cell_size}")
    lines.append(f"#define FLASHLINK_NAME_SIZE       {name_size}")
    lines.append(f"#define FLASHLINK_CELL_DATA_SIZE  {cell_data_size}")
    lines.append("")
    lines.append(f"#define STORAGE_FLASH_LINK_READ_FUNC    {read_func}")
    lines.append(f"#define STORAGE_FLASH_LINK_PROG_FUNC    {prog_func}")
    lines.append(f"#define STORAGE_FLASH_LINK_ERASE_FUNC   {erase_func}")
    lines.append(f"#define STORAGE_FLASH_LINK_SYNC_FUNC    {sync_func}")
    lines.append("")
    lines.append("#endif /* __FS_PORT_CONFIG_H__ */")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate fs_port_config.h from JSON description"
    )
    parser.add_argument(
        "--json",
        required=True,
        help="Path to JSON config file (containing 'store', 'customer', 'version', ...).",
    )
    parser.add_argument(
        "--out",
        default="fs_port_config.h",
        help="Output header path (default: fs_port_config.h in current dir).",
    )
    args = parser.parse_args()

    with open(args.json, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    script_name = os.path.basename(__file__)
    text = generate_header_text(cfg, script_name)

    out_path = args.out
    # Ensure directory exists
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"Generated {out_path}")


if __name__ == "__main__":
    main()